language: go
sudo: required
dist: trusty
go:
- 1.9.x
services:
- redis-server
- postgresql
- docker
addons:
  postgresql: '9.5'
env:
  matrix:
    secure: yjfkM6ZJxfL8nrZkNQskq6yzqUPjm/T8lPqZFGjPCNmKn0X8jTPb0W54RPByjqDRQZLP1VzQXrj1ltm+1VMMq66nAZP8kN3l7VpHwmRNyErwFeUZZN5AxoDXB2Ed5cUPAw1GULMjj7e/y/92l8sudcsztXF0ipTSuvpcBkq0QpULFh4VCaoSS0Lbtbo9olc/s78X2TeMr9J/VWi3TLMWIMBQowvObqVb0strcOEpqlbJ9+siciLTTwcczC63/P06BzFtTilpQegaJKtFp+EYqbSORfiNOV2vgDwRsYneIGTd9RtF7AAdYCmP8674ERgkAO+rDi043Wr3vyTmTHp53QrZBbVxfyW3PgoiuGJzj0/ZupS20n14FYnjxo7ziyzUG6K/lWrzNz20qiQn4KPFwXGmTpFW47abWgUR8VyELlUIUa3XhkoKzrxDSJ03bh1aEdS219nWRzljTlCgC58g3ilDOhAE9+4re4UnVAwZOl7QryUaHmz4k6YRJiw8cN2jtlPOjpaobfoYTN0PBVstqTBMqtV6nHDKePcST8od88Zf9EvERZL5jXwrDKmhuCWcDGApUS5hJUYMWIf/iNEWIMSuOs/ulzggdNCx9teqphEmMx59loMh4bUrayrx02ft7PJy6NhEGKXyXG1HquYk+g5pHfGg5G4eNjMLK13MHqg=
install:
- echo "install nothing!"
script:
- echo "no tests!"
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: eu-central-1
  app: appserver-backend
  env: appserver-backend-dev
  on:
    branch: post_user
after_sucess:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region eu-central-1)
- docker build -t maliot .
- docker tag maliot:latest 228684700718.dkr.ecr.eu-central-1.amazonaws.com/maliot:latest
- docker push 228684700718.dkr.ecr.eu-central-1.amazonaws.com/maliot:latest
