language: go
sudo: required
dist: trusty
go:
- 1.9.x
services:
- redis-server
- postgresql
- docker
addons:
  postgresql: '9.5'
install:
- echo "install nothing!"
script:
- echo "no tests!"
before_deploy:
- rvm 1.9.3 do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: AKIAJL2ERUB644Z3MALA
  secret_access_key:
    secure: Ofgvp0lFlCPEhxgk0j9S9T2a2Gqaa/YXSYSIsHivI8J+QbhQhq4j2i6J8nmBaYaJaIFLptQLYK23WQQrJMa24G11xbwE/Z8l5BrFSlGI0u3ginE1uQ9ghfzc3bijr1X4wdW8OGqjDW1qNlmHr8l056Ms8WUkhPK6P7ZW7Br8rB+ZGG1xzb2YlgpkC/coldjFk4NCNuqZqu99Bv4LD/WkGydrExhHhDNFGZ/NN1s//axaWhIsjGVOxBenSCi1KeI2Lrtb4XzAHn02NkuMgNompgOzRGxYCEQK9NLHdkfB7eHxGGoaU2/TIFQSQQIO6kt/D7QGJHx7+uDbYC02jFSogFd9rt+rHD/O8vP3tYaWmzhd83jnZc3edrrFRamTcG5ByfmzrhK5orMUn1rBwH4M1Tzku+8q9ds6EfnmwEbyyP2svu1dikYLffth2wvoJXpr4iNk9csKl52q1Ndq5KJ4A41PK7+0rf6bR14QgCjQRoN4zZsY0cwqj21blCGdSOYN0FGxmeSvVOmNgqsoB5Y6cAFbcH6ytGsATwZz3hqroylsVQAmIPy+1hcPKOSB5d5V3v2WXJFCHAVcQSqg6UuQoTTyWaGYkARScYXYpsylFXeC5b0qvfXLxa2i+sJU2vQeMJnhq6aVEPuFjjLMZ4xALmghLQGl5mO7tUZpmcVHTQc=
  bucket: elasticbeanstalk-eu-central-1-228684700718
  acl: private
  on:
    repo: gusseleet/lora-app-server
    branch: post_user
