language: go
sudo: required
dist: trusty
go:
- 1.9.x
services:
- redis-server
- postgresql
- docker
addons:
  postgresql: '9.5'
env:
  matrix:
    secure: yjfkM6ZJxfL8nrZkNQskq6yzqUPjm/T8lPqZFGjPCNmKn0X8jTPb0W54RPByjqDRQZLP1VzQXrj1ltm+1VMMq66nAZP8kN3l7VpHwmRNyErwFeUZZN5AxoDXB2Ed5cUPAw1GULMjj7e/y/92l8sudcsztXF0ipTSuvpcBkq0QpULFh4VCaoSS0Lbtbo9olc/s78X2TeMr9J/VWi3TLMWIMBQowvObqVb0strcOEpqlbJ9+siciLTTwcczC63/P06BzFtTilpQegaJKtFp+EYqbSORfiNOV2vgDwRsYneIGTd9RtF7AAdYCmP8674ERgkAO+rDi043Wr3vyTmTHp53QrZBbVxfyW3PgoiuGJzj0/ZupS20n14FYnjxo7ziyzUG6K/lWrzNz20qiQn4KPFwXGmTpFW47abWgUR8VyELlUIUa3XhkoKzrxDSJ03bh1aEdS219nWRzljTlCgC58g3ilDOhAE9+4re4UnVAwZOl7QryUaHmz4k6YRJiw8cN2jtlPOjpaobfoYTN0PBVstqTBMqtV6nHDKePcST8od88Zf9EvERZL5jXwrDKmhuCWcDGApUS5hJUYMWIf/iNEWIMSuOs/ulzggdNCx9teqphEmMx59loMh4bUrayrx02ft7PJy6NhEGKXyXG1HquYk+g5pHfGg5G4eNjMLK13MHqg=
install:
- echo "install nothing!"
script:
- echo "no tests!"
deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAJL2ERUB644Z3MALA"
  secret_access_key:
    secure: "bEVyF2vdGZI3D8O/93C5DMV++PJ7BkA89fsB8QVAt132v2KS0ZxxDjBhPshlNvfQAlR9zszsew13+mzgmUIa9pB9PQi54cFZhAb7Yh16/t+tgniQ+y95wkfMVC+AMkO728+nOtrB8nIdzkEjHekI/GEZ/TRqqaWvzmHS24LRw5fKEjeULv+BriQ0mJwkXOIwW5969lWlI+CTL6dx47Oc3NCVerw8Gg+njHSYFW0N86h7sAp0xjQNJ5e9676NM5MoLA7MSpZUNMkvVOVm/2YHy6ZoEcybgiK3rH+HdQMwLzLXYjvX93mbxRK8ov3lgW0UaL1pFSQlRDSwjvTiDAaiGkUuc7jitJKSs39fkxucTuRn9xhLYwmioVeTjDW1qt02W7OmZ0so353n0bOM95Ryiw3O5qb65adAHIZuj2OxAvByGVA6GiZX9cSO+3TWz0Non9qVp+W6d6MGjEgNceAGR8ShFzouoMth0/jS4jZuUv9y5WAJGbmawIzg4JohvoGH+YBmwSsALM/lz7PjCvtyLXtBANpALhzBV5R2CC4h2hdnvqwtj7lWbtyIqXkw9NusOSSHgzik9umcsCKn0eovUUcGGWMXhw+038WKrTaCflwYv9wluQ6HW5gRBycxTSPorkSkQByur4O1EGAfhNMT6kPg7GsOQ5Js2KFBtpghgU8="

  region: eu-central-1
  app: appserver-backend
  env: appserver-backend-dev
  on:
    branch: post_user

