version: "2"
services:
  appserver:
    build: 
      context: .
      dockerfile: Dockerfile-devel
    command: make serve
    volumes:
    - ./:/go/src/github.com/gusseleet/lora-app-server
    - /go/src/github.com/gusseleet/lora-app-server/vendor
    - /go/src/github.com/gusseleet/lora-app-server/ui/node_modules
    links:
    - postgres
    - redis
    - mosquitto
    environment:
    - POSTGRES_DSN=postgres://loraserver:loraserver@postgres/loraserver?sslmode=disable
    - REDIS_URL=redis://redis:6379
    - MQTT_SERVER=tcp://mosquitto:1883
    - TEST_POSTGRES_DSN=postgres://loraserver:loraserver@postgres/loraserver_test?sslmode=disable
    - TEST_REDIS_URL=redis://redis:6379
    - TEST_MQTT_SERVER=tcp://mosquitto:1883
    - JWT_SECRET=verysecret
    - HTTP_TLS_CERT=/etc/lora-app-server/certs/http.pem
    - HTTP_TLS_KEY=/etc/lora-app-server/certs/http-key.pem
    - AS_PUBLIC_SERVER=appserver:8001
    - DB_AUTOMIGRATE=true
    ports:
      - 8080:8080

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=loraserver
      - POSTGRES_USER=loraserver
      - POSTGRES_DB=loraserver_test
    ports:
      - 5432:5432

  redis:
    image: redis:3.0.7-alpine

  mosquitto:
    image: ansi/mosquitto
