version: "2"
services:
  appserver:
    build: 
      context: .
      dockerfile: Dockerfile-devel
    command: make serve
    image: maliot
    volumes:
    - ./:/go/src/github.com/gusseleet/lora-app-server
    - /go/src/github.com/gusseleet/lora-app-server/vendor
    - /go/src/github.com/gusseleet/lora-app-server/ui/node_modules
    - ./lora-app-server.toml:/etc/lora-app-server/lora-app-server.toml
    links:
    - postgres
    - redis
    - mosquitto
    ports:
      - 8080:8080

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=loraserver
      - POSTGRES_USER=loraserver
      - POSTGRES_DB=loraserver
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:3.0.7-alpine

  mosquitto:
    image: ansi/mosquitto
