version: "2"
services:
  appserver:
    build:
      context: .
      dockerfile: Dockerfile-devel
    command: make serve
    volumes:
      - ./:/go/src/github.com/gusseleet/lora-app-server
      - /go/src/github.com/gusseleet/lora-app-server/vendor
      - /go/src/github.com/gusseleet/lora-app-server/ui/node_modules
    environment:
      - DB_AUTOMIGRATE=true
      - POSTGRES_DSN=postgres://${db_user}:${db_pw}@${IP}:5432/loraserver_as?sslmode=disable
      - REDIS_URL=redis://${IP}:6379
      - MQTT_SERVER=tcp://${IP}:1883
      - TEST_POSTGRES_DSN=postgres://${db_user}:${db_pw}@${IP}:5432/loraserver_as?sslmode=disable
      - TEST_REDIS_URL=redis://${IP}:6379
      - TEST_MQTT_SERVER=tcp://${IP}:1883
      - JWT_SECRET=verysecret
      - HTTP_TLS_CERT=/etc/lora-app-server/certs/http.pem
      - HTTP_TLS_KEY=/etc/lora-app-server/certs/http-key.pem
      - AS_PUBLIC_SERVER=appserver:8001
    ports:
      - 8080:8080
