// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type IntegrationKind int32

const (
	IntegrationKind_HTTP IntegrationKind = 0
)

var IntegrationKind_name = map[int32]string{
	0: "HTTP",
}
var IntegrationKind_value = map[string]int32{
	"HTTP": 0,
}

func (x IntegrationKind) String() string {
	return proto.EnumName(IntegrationKind_name, int32(x))
}
func (IntegrationKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type CreateApplicationRequest struct {
	// Name of the application (must be unique).
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Description of the application.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// ID of the organization to which the application belongs.
	OrganizationID int64 `protobuf:"varint,14,opt,name=organizationID" json:"organizationID,omitempty"`
	// ID of the service profile.
	ServiceProfileID string `protobuf:"bytes,15,opt,name=serviceProfileID" json:"serviceProfileID,omitempty"`
	// Payload codec.
	PayloadCodec string `protobuf:"bytes,16,opt,name=payloadCodec" json:"payloadCodec,omitempty"`
	// Payload encoder script.
	PayloadEncoderScript string `protobuf:"bytes,17,opt,name=payloadEncoderScript" json:"payloadEncoderScript,omitempty"`
	// Payload decoder script.
	PayloadDecoderScript string `protobuf:"bytes,18,opt,name=payloadDecoderScript" json:"payloadDecoderScript,omitempty"`
	// Gateway network ID
	GatewayNetworkID int64 `protobuf:"varint,19,opt,name=gatewayNetworkID" json:"gatewayNetworkID,omitempty"`
	// Payment plan ID
	PaymentPlanID int64 `protobuf:"varint,20,opt,name=paymentPlanID" json:"paymentPlanID,omitempty"`
}

func (m *CreateApplicationRequest) Reset()                    { *m = CreateApplicationRequest{} }
func (m *CreateApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateApplicationRequest) ProtoMessage()               {}
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CreateApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateApplicationRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateApplicationRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *CreateApplicationRequest) GetServiceProfileID() string {
	if m != nil {
		return m.ServiceProfileID
	}
	return ""
}

func (m *CreateApplicationRequest) GetPayloadCodec() string {
	if m != nil {
		return m.PayloadCodec
	}
	return ""
}

func (m *CreateApplicationRequest) GetPayloadEncoderScript() string {
	if m != nil {
		return m.PayloadEncoderScript
	}
	return ""
}

func (m *CreateApplicationRequest) GetPayloadDecoderScript() string {
	if m != nil {
		return m.PayloadDecoderScript
	}
	return ""
}

func (m *CreateApplicationRequest) GetGatewayNetworkID() int64 {
	if m != nil {
		return m.GatewayNetworkID
	}
	return 0
}

func (m *CreateApplicationRequest) GetPaymentPlanID() int64 {
	if m != nil {
		return m.PaymentPlanID
	}
	return 0
}

type CreateApplicationResponse struct {
	// ID of the application that was created.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateApplicationResponse) Reset()                    { *m = CreateApplicationResponse{} }
func (m *CreateApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateApplicationResponse) ProtoMessage()               {}
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *CreateApplicationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetApplicationRequest struct {
	// Name of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetApplicationRequest) Reset()                    { *m = GetApplicationRequest{} }
func (m *GetApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationRequest) ProtoMessage()               {}
func (*GetApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetApplicationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetApplicationResponse struct {
	// ID of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Name of the application.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Description of the application.
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// ID of the organization to which the application belongs.
	OrganizationID int64 `protobuf:"varint,14,opt,name=organizationID" json:"organizationID,omitempty"`
	// ID of the service profile.
	ServiceProfileID string `protobuf:"bytes,15,opt,name=serviceProfileID" json:"serviceProfileID,omitempty"`
	// Payload codec.
	PayloadCodec string `protobuf:"bytes,16,opt,name=payloadCodec" json:"payloadCodec,omitempty"`
	// Payload encoder script.
	PayloadEncoderScript string `protobuf:"bytes,17,opt,name=payloadEncoderScript" json:"payloadEncoderScript,omitempty"`
	// Payload decoder script.
	PayloadDecoderScript string `protobuf:"bytes,18,opt,name=payloadDecoderScript" json:"payloadDecoderScript,omitempty"`
	// Gateway network ID
	GatewayNetworkID int64 `protobuf:"varint,19,opt,name=gatewayNetworkID" json:"gatewayNetworkID,omitempty"`
	// Payment plan ID
	PaymentPlanID int64 `protobuf:"varint,20,opt,name=paymentPlanID" json:"paymentPlanID,omitempty"`
}

func (m *GetApplicationResponse) Reset()                    { *m = GetApplicationResponse{} }
func (m *GetApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationResponse) ProtoMessage()               {}
func (*GetApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetApplicationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetApplicationResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetApplicationResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetApplicationResponse) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *GetApplicationResponse) GetServiceProfileID() string {
	if m != nil {
		return m.ServiceProfileID
	}
	return ""
}

func (m *GetApplicationResponse) GetPayloadCodec() string {
	if m != nil {
		return m.PayloadCodec
	}
	return ""
}

func (m *GetApplicationResponse) GetPayloadEncoderScript() string {
	if m != nil {
		return m.PayloadEncoderScript
	}
	return ""
}

func (m *GetApplicationResponse) GetPayloadDecoderScript() string {
	if m != nil {
		return m.PayloadDecoderScript
	}
	return ""
}

func (m *GetApplicationResponse) GetGatewayNetworkID() int64 {
	if m != nil {
		return m.GatewayNetworkID
	}
	return 0
}

func (m *GetApplicationResponse) GetPaymentPlanID() int64 {
	if m != nil {
		return m.PaymentPlanID
	}
	return 0
}

type UpdateApplicationRequest struct {
	// ID of the application to update.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Name of the application (must be unique).
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Description of the application.
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// ID of the service profile.
	ServiceProfileID string `protobuf:"bytes,15,opt,name=serviceProfileID" json:"serviceProfileID,omitempty"`
	// Payload codec.
	PayloadCodec string `protobuf:"bytes,16,opt,name=payloadCodec" json:"payloadCodec,omitempty"`
	// Payload encoder script.
	PayloadEncoderScript string `protobuf:"bytes,17,opt,name=payloadEncoderScript" json:"payloadEncoderScript,omitempty"`
	// Payload decoder script.
	PayloadDecoderScript string `protobuf:"bytes,18,opt,name=payloadDecoderScript" json:"payloadDecoderScript,omitempty"`
	// Gateway network ID
	GatewayNetworkID int64 `protobuf:"varint,19,opt,name=gatewayNetworkID" json:"gatewayNetworkID,omitempty"`
	// Payment plan ID
	PaymentPlanID int64 `protobuf:"varint,20,opt,name=paymentPlanID" json:"paymentPlanID,omitempty"`
}

func (m *UpdateApplicationRequest) Reset()                    { *m = UpdateApplicationRequest{} }
func (m *UpdateApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateApplicationRequest) ProtoMessage()               {}
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *UpdateApplicationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateApplicationRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateApplicationRequest) GetServiceProfileID() string {
	if m != nil {
		return m.ServiceProfileID
	}
	return ""
}

func (m *UpdateApplicationRequest) GetPayloadCodec() string {
	if m != nil {
		return m.PayloadCodec
	}
	return ""
}

func (m *UpdateApplicationRequest) GetPayloadEncoderScript() string {
	if m != nil {
		return m.PayloadEncoderScript
	}
	return ""
}

func (m *UpdateApplicationRequest) GetPayloadDecoderScript() string {
	if m != nil {
		return m.PayloadDecoderScript
	}
	return ""
}

func (m *UpdateApplicationRequest) GetGatewayNetworkID() int64 {
	if m != nil {
		return m.GatewayNetworkID
	}
	return 0
}

func (m *UpdateApplicationRequest) GetPaymentPlanID() int64 {
	if m != nil {
		return m.PaymentPlanID
	}
	return 0
}

type UpdateApplicationResponse struct {
}

func (m *UpdateApplicationResponse) Reset()                    { *m = UpdateApplicationResponse{} }
func (m *UpdateApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateApplicationResponse) ProtoMessage()               {}
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type DeleteApplicationRequest struct {
	// ID of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteApplicationRequest) Reset()                    { *m = DeleteApplicationRequest{} }
func (m *DeleteApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteApplicationRequest) ProtoMessage()               {}
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *DeleteApplicationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteApplicationResponse struct {
}

func (m *DeleteApplicationResponse) Reset()                    { *m = DeleteApplicationResponse{} }
func (m *DeleteApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteApplicationResponse) ProtoMessage()               {}
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type ListApplicationRequest struct {
	// Max number of applications to return in the result-test.
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// ID of the organization to filter on.
	OrganizationID int64 `protobuf:"varint,3,opt,name=organizationID" json:"organizationID,omitempty"`
}

func (m *ListApplicationRequest) Reset()                    { *m = ListApplicationRequest{} }
func (m *ListApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationRequest) ProtoMessage()               {}
func (*ListApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ListApplicationRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListApplicationRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

type ListApplicationsByGWNRequest struct {
	// Max number of applications to return in the result-test.
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// ID of the Gateway network to filter on.
	GatewayNetworkID int64 `protobuf:"varint,4,opt,name=gatewayNetworkID" json:"gatewayNetworkID,omitempty"`
}

func (m *ListApplicationsByGWNRequest) Reset()                    { *m = ListApplicationsByGWNRequest{} }
func (m *ListApplicationsByGWNRequest) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationsByGWNRequest) ProtoMessage()               {}
func (*ListApplicationsByGWNRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ListApplicationsByGWNRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationsByGWNRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListApplicationsByGWNRequest) GetGatewayNetworkID() int64 {
	if m != nil {
		return m.GatewayNetworkID
	}
	return 0
}

type ApplicationListItem struct {
	// ID of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Name of the application.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Description of the application.
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// ID of the organization to which the application belongs.
	OrganizationID int64 `protobuf:"varint,14,opt,name=organizationID" json:"organizationID,omitempty"`
	// ID of the service profile.
	ServiceProfileID string `protobuf:"bytes,15,opt,name=serviceProfileID" json:"serviceProfileID,omitempty"`
	// Service-profile name.
	ServiceProfileName string `protobuf:"bytes,16,opt,name=serviceProfileName" json:"serviceProfileName,omitempty"`
	// Gateway network ID
	GatewayNetworkID int64 `protobuf:"varint,19,opt,name=gatewayNetworkID" json:"gatewayNetworkID,omitempty"`
	// Payment plan ID
	PaymentPlanID int64 `protobuf:"varint,20,opt,name=paymentPlanID" json:"paymentPlanID,omitempty"`
}

func (m *ApplicationListItem) Reset()                    { *m = ApplicationListItem{} }
func (m *ApplicationListItem) String() string            { return proto.CompactTextString(m) }
func (*ApplicationListItem) ProtoMessage()               {}
func (*ApplicationListItem) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ApplicationListItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApplicationListItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationListItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ApplicationListItem) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *ApplicationListItem) GetServiceProfileID() string {
	if m != nil {
		return m.ServiceProfileID
	}
	return ""
}

func (m *ApplicationListItem) GetServiceProfileName() string {
	if m != nil {
		return m.ServiceProfileName
	}
	return ""
}

func (m *ApplicationListItem) GetGatewayNetworkID() int64 {
	if m != nil {
		return m.GatewayNetworkID
	}
	return 0
}

func (m *ApplicationListItem) GetPaymentPlanID() int64 {
	if m != nil {
		return m.PaymentPlanID
	}
	return 0
}

type ListApplicationResponse struct {
	// Total number of applications available within the result-set.
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// Applications within this result-set.
	Result []*ApplicationListItem `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListApplicationResponse) Reset()                    { *m = ListApplicationResponse{} }
func (m *ListApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationResponse) ProtoMessage()               {}
func (*ListApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *ListApplicationResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListApplicationResponse) GetResult() []*ApplicationListItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type EmptyResponse struct {
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type HTTPIntegrationHeader struct {
	// Key
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// Value
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *HTTPIntegrationHeader) Reset()                    { *m = HTTPIntegrationHeader{} }
func (m *HTTPIntegrationHeader) String() string            { return proto.CompactTextString(m) }
func (*HTTPIntegrationHeader) ProtoMessage()               {}
func (*HTTPIntegrationHeader) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *HTTPIntegrationHeader) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HTTPIntegrationHeader) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HTTPIntegration struct {
	// The id of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The headers to use when making HTTP callbacks.
	Headers []*HTTPIntegrationHeader `protobuf:"bytes,2,rep,name=headers" json:"headers,omitempty"`
	// The URL to call for uplink data.
	DataUpURL string `protobuf:"bytes,3,opt,name=dataUpURL" json:"dataUpURL,omitempty"`
	// The URL to call for join notifications.
	JoinNotificationURL string `protobuf:"bytes,4,opt,name=joinNotificationURL" json:"joinNotificationURL,omitempty"`
	// The URL to call for ACK notifications (for confirmed downlink data).
	AckNotificationURL string `protobuf:"bytes,5,opt,name=ackNotificationURL" json:"ackNotificationURL,omitempty"`
	// The URL to call for error notifications.
	ErrorNotificationURL string `protobuf:"bytes,6,opt,name=errorNotificationURL" json:"errorNotificationURL,omitempty"`
}

func (m *HTTPIntegration) Reset()                    { *m = HTTPIntegration{} }
func (m *HTTPIntegration) String() string            { return proto.CompactTextString(m) }
func (*HTTPIntegration) ProtoMessage()               {}
func (*HTTPIntegration) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *HTTPIntegration) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HTTPIntegration) GetHeaders() []*HTTPIntegrationHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPIntegration) GetDataUpURL() string {
	if m != nil {
		return m.DataUpURL
	}
	return ""
}

func (m *HTTPIntegration) GetJoinNotificationURL() string {
	if m != nil {
		return m.JoinNotificationURL
	}
	return ""
}

func (m *HTTPIntegration) GetAckNotificationURL() string {
	if m != nil {
		return m.AckNotificationURL
	}
	return ""
}

func (m *HTTPIntegration) GetErrorNotificationURL() string {
	if m != nil {
		return m.ErrorNotificationURL
	}
	return ""
}

type GetHTTPIntegrationRequest struct {
	// The id of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetHTTPIntegrationRequest) Reset()                    { *m = GetHTTPIntegrationRequest{} }
func (m *GetHTTPIntegrationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHTTPIntegrationRequest) ProtoMessage()               {}
func (*GetHTTPIntegrationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *GetHTTPIntegrationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteIntegrationRequest struct {
	// The id of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteIntegrationRequest) Reset()                    { *m = DeleteIntegrationRequest{} }
func (m *DeleteIntegrationRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteIntegrationRequest) ProtoMessage()               {}
func (*DeleteIntegrationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *DeleteIntegrationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListIntegrationRequest struct {
	// The id of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListIntegrationRequest) Reset()                    { *m = ListIntegrationRequest{} }
func (m *ListIntegrationRequest) String() string            { return proto.CompactTextString(m) }
func (*ListIntegrationRequest) ProtoMessage()               {}
func (*ListIntegrationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *ListIntegrationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListIntegrationResponse struct {
	// The integration kinds associated with the application.
	Kinds []IntegrationKind `protobuf:"varint,1,rep,packed,name=kinds,enum=api.IntegrationKind" json:"kinds,omitempty"`
}

func (m *ListIntegrationResponse) Reset()                    { *m = ListIntegrationResponse{} }
func (m *ListIntegrationResponse) String() string            { return proto.CompactTextString(m) }
func (*ListIntegrationResponse) ProtoMessage()               {}
func (*ListIntegrationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *ListIntegrationResponse) GetKinds() []IntegrationKind {
	if m != nil {
		return m.Kinds
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateApplicationRequest)(nil), "api.CreateApplicationRequest")
	proto.RegisterType((*CreateApplicationResponse)(nil), "api.CreateApplicationResponse")
	proto.RegisterType((*GetApplicationRequest)(nil), "api.GetApplicationRequest")
	proto.RegisterType((*GetApplicationResponse)(nil), "api.GetApplicationResponse")
	proto.RegisterType((*UpdateApplicationRequest)(nil), "api.UpdateApplicationRequest")
	proto.RegisterType((*UpdateApplicationResponse)(nil), "api.UpdateApplicationResponse")
	proto.RegisterType((*DeleteApplicationRequest)(nil), "api.DeleteApplicationRequest")
	proto.RegisterType((*DeleteApplicationResponse)(nil), "api.DeleteApplicationResponse")
	proto.RegisterType((*ListApplicationRequest)(nil), "api.ListApplicationRequest")
	proto.RegisterType((*ListApplicationsByGWNRequest)(nil), "api.ListApplicationsByGWNRequest")
	proto.RegisterType((*ApplicationListItem)(nil), "api.ApplicationListItem")
	proto.RegisterType((*ListApplicationResponse)(nil), "api.ListApplicationResponse")
	proto.RegisterType((*EmptyResponse)(nil), "api.EmptyResponse")
	proto.RegisterType((*HTTPIntegrationHeader)(nil), "api.HTTPIntegrationHeader")
	proto.RegisterType((*HTTPIntegration)(nil), "api.HTTPIntegration")
	proto.RegisterType((*GetHTTPIntegrationRequest)(nil), "api.GetHTTPIntegrationRequest")
	proto.RegisterType((*DeleteIntegrationRequest)(nil), "api.DeleteIntegrationRequest")
	proto.RegisterType((*ListIntegrationRequest)(nil), "api.ListIntegrationRequest")
	proto.RegisterType((*ListIntegrationResponse)(nil), "api.ListIntegrationResponse")
	proto.RegisterEnum("api.IntegrationKind", IntegrationKind_name, IntegrationKind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Application service

type ApplicationClient interface {
	// Create creates the given application.
	Create(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error)
	// Get returns the requested application.
	Get(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*GetApplicationResponse, error)
	// Update updates the given application.
	Update(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*UpdateApplicationResponse, error)
	// Delete deletes the given application.
	Delete(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error)
	// List lists the available applications.
	List(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error)
	// ListOnGatewayNetwork lists the available applications based on gateway network id.
	ListOnGatewayNetwork(ctx context.Context, in *ListApplicationsByGWNRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error)
	// CreateHTTPIntegration creates an HTTP application-integration.
	CreateHTTPIntegration(ctx context.Context, in *HTTPIntegration, opts ...grpc.CallOption) (*EmptyResponse, error)
	// GetHTTPIntegration returns the HTTP application-itegration.
	GetHTTPIntegration(ctx context.Context, in *GetHTTPIntegrationRequest, opts ...grpc.CallOption) (*HTTPIntegration, error)
	// UpdateHTTPIntegration updates the HTTP application-integration.
	UpdateHTTPIntegration(ctx context.Context, in *HTTPIntegration, opts ...grpc.CallOption) (*EmptyResponse, error)
	// DeleteIntegration deletes the application-integration of the given type.
	DeleteHTTPIntegration(ctx context.Context, in *DeleteIntegrationRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// ListIntegrations lists all configured integrations.
	ListIntegrations(ctx context.Context, in *ListIntegrationRequest, opts ...grpc.CallOption) (*ListIntegrationResponse, error)
}

type applicationClient struct {
	cc *grpc.ClientConn
}

func NewApplicationClient(cc *grpc.ClientConn) ApplicationClient {
	return &applicationClient{cc}
}

func (c *applicationClient) Create(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error) {
	out := new(CreateApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) Get(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*GetApplicationResponse, error) {
	out := new(GetApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) Update(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*UpdateApplicationResponse, error) {
	out := new(UpdateApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) Delete(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error) {
	out := new(DeleteApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) List(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error) {
	out := new(ListApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) ListOnGatewayNetwork(ctx context.Context, in *ListApplicationsByGWNRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error) {
	out := new(ListApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/ListOnGatewayNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) CreateHTTPIntegration(ctx context.Context, in *HTTPIntegration, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/api.Application/CreateHTTPIntegration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) GetHTTPIntegration(ctx context.Context, in *GetHTTPIntegrationRequest, opts ...grpc.CallOption) (*HTTPIntegration, error) {
	out := new(HTTPIntegration)
	err := grpc.Invoke(ctx, "/api.Application/GetHTTPIntegration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) UpdateHTTPIntegration(ctx context.Context, in *HTTPIntegration, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/api.Application/UpdateHTTPIntegration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) DeleteHTTPIntegration(ctx context.Context, in *DeleteIntegrationRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/api.Application/DeleteHTTPIntegration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) ListIntegrations(ctx context.Context, in *ListIntegrationRequest, opts ...grpc.CallOption) (*ListIntegrationResponse, error) {
	out := new(ListIntegrationResponse)
	err := grpc.Invoke(ctx, "/api.Application/ListIntegrations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Application service

type ApplicationServer interface {
	// Create creates the given application.
	Create(context.Context, *CreateApplicationRequest) (*CreateApplicationResponse, error)
	// Get returns the requested application.
	Get(context.Context, *GetApplicationRequest) (*GetApplicationResponse, error)
	// Update updates the given application.
	Update(context.Context, *UpdateApplicationRequest) (*UpdateApplicationResponse, error)
	// Delete deletes the given application.
	Delete(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	// List lists the available applications.
	List(context.Context, *ListApplicationRequest) (*ListApplicationResponse, error)
	// ListOnGatewayNetwork lists the available applications based on gateway network id.
	ListOnGatewayNetwork(context.Context, *ListApplicationsByGWNRequest) (*ListApplicationResponse, error)
	// CreateHTTPIntegration creates an HTTP application-integration.
	CreateHTTPIntegration(context.Context, *HTTPIntegration) (*EmptyResponse, error)
	// GetHTTPIntegration returns the HTTP application-itegration.
	GetHTTPIntegration(context.Context, *GetHTTPIntegrationRequest) (*HTTPIntegration, error)
	// UpdateHTTPIntegration updates the HTTP application-integration.
	UpdateHTTPIntegration(context.Context, *HTTPIntegration) (*EmptyResponse, error)
	// DeleteIntegration deletes the application-integration of the given type.
	DeleteHTTPIntegration(context.Context, *DeleteIntegrationRequest) (*EmptyResponse, error)
	// ListIntegrations lists all configured integrations.
	ListIntegrations(context.Context, *ListIntegrationRequest) (*ListIntegrationResponse, error)
}

func RegisterApplicationServer(s *grpc.Server, srv ApplicationServer) {
	s.RegisterService(&_Application_serviceDesc, srv)
}

func _Application_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).Create(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).Get(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).Update(ctx, req.(*UpdateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).Delete(ctx, req.(*DeleteApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).List(ctx, req.(*ListApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_ListOnGatewayNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsByGWNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).ListOnGatewayNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/ListOnGatewayNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).ListOnGatewayNetwork(ctx, req.(*ListApplicationsByGWNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_CreateHTTPIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPIntegration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).CreateHTTPIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/CreateHTTPIntegration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).CreateHTTPIntegration(ctx, req.(*HTTPIntegration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_GetHTTPIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHTTPIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetHTTPIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/GetHTTPIntegration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetHTTPIntegration(ctx, req.(*GetHTTPIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_UpdateHTTPIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPIntegration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).UpdateHTTPIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/UpdateHTTPIntegration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).UpdateHTTPIntegration(ctx, req.(*HTTPIntegration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_DeleteHTTPIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).DeleteHTTPIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/DeleteHTTPIntegration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).DeleteHTTPIntegration(ctx, req.(*DeleteIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_ListIntegrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).ListIntegrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/ListIntegrations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).ListIntegrations(ctx, req.(*ListIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Application_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Application",
	HandlerType: (*ApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Application_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Application_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Application_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Application_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Application_List_Handler,
		},
		{
			MethodName: "ListOnGatewayNetwork",
			Handler:    _Application_ListOnGatewayNetwork_Handler,
		},
		{
			MethodName: "CreateHTTPIntegration",
			Handler:    _Application_CreateHTTPIntegration_Handler,
		},
		{
			MethodName: "GetHTTPIntegration",
			Handler:    _Application_GetHTTPIntegration_Handler,
		},
		{
			MethodName: "UpdateHTTPIntegration",
			Handler:    _Application_UpdateHTTPIntegration_Handler,
		},
		{
			MethodName: "DeleteHTTPIntegration",
			Handler:    _Application_DeleteHTTPIntegration_Handler,
		},
		{
			MethodName: "ListIntegrations",
			Handler:    _Application_ListIntegrations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}

func init() { proto.RegisterFile("application.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 982 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcb, 0x6e, 0x23, 0x45,
	0x14, 0xc5, 0x6e, 0xc7, 0x90, 0x1b, 0x26, 0x71, 0x2a, 0x8e, 0xe9, 0x74, 0x4c, 0x94, 0xf4, 0xf0,
	0x30, 0x1e, 0x11, 0x47, 0x19, 0x56, 0x6c, 0x10, 0x13, 0x47, 0x1e, 0x8b, 0x51, 0x88, 0x9a, 0x89,
	0xd8, 0x20, 0xa4, 0xc2, 0x5d, 0xf1, 0xd4, 0xb8, 0xdd, 0xd5, 0x74, 0x97, 0x33, 0x78, 0x80, 0x4d,
	0xb6, 0x6c, 0x90, 0xf8, 0x12, 0xbe, 0x85, 0x5f, 0x60, 0xc5, 0x9a, 0x0f, 0x40, 0xf5, 0x70, 0xd2,
	0x8f, 0x6a, 0x61, 0x18, 0x90, 0x66, 0x31, 0x3b, 0xf7, 0xbd, 0xa7, 0xee, 0xa3, 0xce, 0xa9, 0x5b,
	0x65, 0xd8, 0xc4, 0x51, 0x14, 0xd0, 0x11, 0xe6, 0x94, 0x85, 0x87, 0x51, 0xcc, 0x38, 0x43, 0x16,
	0x8e, 0xa8, 0xd3, 0x1e, 0x33, 0x36, 0x0e, 0x48, 0x0f, 0x47, 0xb4, 0x87, 0xc3, 0x90, 0x71, 0x89,
	0x48, 0x14, 0xc4, 0xbd, 0xb6, 0xc0, 0x3e, 0x89, 0x09, 0xe6, 0xe4, 0xd3, 0xdb, 0xe5, 0x1e, 0xf9,
	0x76, 0x46, 0x12, 0x8e, 0x10, 0xd4, 0x42, 0x3c, 0x25, 0x76, 0x65, 0xbf, 0xd2, 0x59, 0xf5, 0xe4,
	0x6f, 0xb4, 0x0f, 0x6b, 0x3e, 0x49, 0x46, 0x31, 0x8d, 0x04, 0xd2, 0xae, 0x4a, 0x57, 0xda, 0x84,
	0xde, 0x83, 0x75, 0x16, 0x8f, 0x71, 0x48, 0x9f, 0xcb, 0x60, 0xc3, 0xbe, 0xbd, 0xbe, 0x5f, 0xe9,
	0x58, 0x5e, 0xce, 0x8a, 0xba, 0xd0, 0x48, 0x48, 0x7c, 0x45, 0x47, 0xe4, 0x3c, 0x66, 0x97, 0x34,
	0x20, 0xc3, 0xbe, 0xbd, 0x21, 0xc3, 0x15, 0xec, 0xc8, 0x85, 0x37, 0x23, 0x3c, 0x0f, 0x18, 0xf6,
	0x4f, 0x98, 0x4f, 0x46, 0x76, 0x43, 0xe2, 0x32, 0x36, 0x74, 0x0c, 0x4d, 0xfd, 0x7d, 0x1a, 0x8e,
	0x98, 0x4f, 0xe2, 0x2f, 0x64, 0x49, 0xf6, 0xa6, 0xc4, 0x1a, 0x7d, 0xa9, 0x35, 0x7d, 0x92, 0x5e,
	0x83, 0x32, 0x6b, 0x32, 0x3e, 0x51, 0xf7, 0x18, 0x73, 0xf2, 0x0c, 0xcf, 0xcf, 0x08, 0x7f, 0xc6,
	0xe2, 0xc9, 0xb0, 0x6f, 0x6f, 0xc9, 0x0e, 0x0b, 0x76, 0xf4, 0x0e, 0xdc, 0x89, 0xf0, 0x7c, 0x4a,
	0x42, 0x7e, 0x1e, 0x60, 0xb1, 0x15, 0x4d, 0x09, 0xcc, 0x1a, 0xdd, 0x7b, 0xb0, 0x63, 0xe0, 0x20,
	0x89, 0x58, 0x98, 0x10, 0xb4, 0x0e, 0x55, 0xea, 0x4b, 0x0a, 0x2c, 0xaf, 0x4a, 0x7d, 0xf7, 0x7d,
	0xd8, 0x1e, 0x10, 0x6e, 0x60, 0x2b, 0x0f, 0xfc, 0xd9, 0x82, 0x56, 0x1e, 0x69, 0x8e, 0x79, 0x43,
	0x74, 0xb5, 0x9c, 0x68, 0xeb, 0x15, 0xd1, 0x2f, 0x4e, 0xf4, 0x1f, 0x55, 0xb0, 0x2f, 0x22, 0xdf,
	0x7c, 0xda, 0xfe, 0x1b, 0x52, 0x5e, 0x6d, 0xf6, 0x62, 0xb3, 0x77, 0x61, 0xc7, 0xb0, 0xd7, 0xea,
	0x04, 0xb8, 0x5d, 0xb0, 0xfb, 0x24, 0x20, 0xcb, 0x10, 0x21, 0x02, 0x19, 0xb0, 0x3a, 0x50, 0x08,
	0xad, 0x47, 0x34, 0x31, 0x9d, 0xc7, 0x26, 0xac, 0x04, 0x74, 0x4a, 0xb9, 0x8e, 0xa4, 0x3e, 0x50,
	0x0b, 0xea, 0xec, 0xf2, 0x32, 0x21, 0x5c, 0xf2, 0x6a, 0x79, 0xfa, 0xcb, 0x70, 0x98, 0x2c, 0xd3,
	0x61, 0x72, 0xbf, 0x83, 0x76, 0x2e, 0x5f, 0xf2, 0x60, 0x3e, 0xf8, 0xf2, 0xec, 0xdf, 0x65, 0x35,
	0xed, 0x7a, 0xcd, 0xbc, 0xeb, 0xee, 0xaf, 0x55, 0xd8, 0x4a, 0xa5, 0x15, 0x55, 0x0c, 0x39, 0x99,
	0xbe, 0xc4, 0xc3, 0xe4, 0x10, 0x50, 0xd6, 0x76, 0x26, 0xea, 0x52, 0x2a, 0x37, 0x78, 0xfe, 0x07,
	0x0d, 0x4e, 0xe0, 0xad, 0x82, 0x3a, 0xf4, 0x0c, 0xde, 0x03, 0xe0, 0x8c, 0xe3, 0xe0, 0x84, 0xcd,
	0xc2, 0x05, 0x5b, 0x29, 0x0b, 0x3a, 0x82, 0x7a, 0x4c, 0x92, 0x59, 0x20, 0x28, 0xb3, 0x3a, 0x6b,
	0xc7, 0xf6, 0x21, 0x8e, 0xe8, 0xa1, 0x81, 0x00, 0x4f, 0xe3, 0xdc, 0x0d, 0xb8, 0x73, 0x3a, 0x8d,
	0xf8, 0xfc, 0x46, 0x9b, 0x9f, 0xc0, 0xf6, 0xc3, 0xc7, 0x8f, 0xcf, 0x87, 0x21, 0x27, 0xe3, 0x58,
	0xae, 0x79, 0x48, 0xb0, 0x4f, 0x62, 0xd4, 0x00, 0x6b, 0x42, 0xe6, 0xfa, 0x5e, 0x17, 0x3f, 0x85,
	0x6c, 0xae, 0x70, 0x30, 0x5b, 0xb0, 0xa6, 0x3e, 0xdc, 0x9f, 0xaa, 0xb0, 0x91, 0x8b, 0x50, 0xa0,
	0xfb, 0x23, 0x78, 0xfd, 0x89, 0x8c, 0x9a, 0xe8, 0x42, 0x1d, 0x59, 0xa8, 0x31, 0xb1, 0xb7, 0x80,
	0xa2, 0x36, 0xac, 0xfa, 0x98, 0xe3, 0x8b, 0xe8, 0xc2, 0x7b, 0xa4, 0xe5, 0x70, 0x6b, 0x40, 0x47,
	0xb0, 0xf5, 0x94, 0xd1, 0xf0, 0x8c, 0x71, 0x7a, 0xa9, 0xbb, 0x15, 0xb8, 0x9a, 0xc4, 0x99, 0x5c,
	0x82, 0x6a, 0x3c, 0x9a, 0xe4, 0x17, 0xac, 0x28, 0xaa, 0x8b, 0x1e, 0x31, 0xa2, 0x48, 0x1c, 0xb3,
	0x38, 0xbf, 0xa2, 0xae, 0x46, 0x94, 0xc9, 0x27, 0xae, 0xe9, 0x01, 0xe1, 0xb9, 0xc6, 0xca, 0x86,
	0xc6, 0xcd, 0x80, 0x59, 0x02, 0xdb, 0x51, 0x33, 0x64, 0x09, 0xe4, 0xa9, 0xd2, 0x53, 0x06, 0xa9,
	0xf5, 0xd4, 0x85, 0x95, 0x09, 0x0d, 0xfd, 0xc4, 0xae, 0xec, 0x5b, 0x9d, 0xf5, 0xe3, 0xa6, 0x64,
	0x21, 0x05, 0xfc, 0x8c, 0x86, 0xbe, 0xa7, 0x20, 0xdd, 0x5d, 0xd8, 0xc8, 0x79, 0xd0, 0x1b, 0x50,
	0x13, 0x9d, 0x35, 0x5e, 0x3b, 0xfe, 0x73, 0x15, 0xd6, 0x52, 0x32, 0x43, 0x04, 0xea, 0xea, 0x75,
	0x82, 0xde, 0x96, 0x31, 0xcb, 0x9e, 0x8b, 0xce, 0x5e, 0x99, 0x5b, 0xcb, 0xb1, 0x7d, 0xfd, 0xdb,
	0xef, 0xbf, 0x54, 0x5b, 0xee, 0xa6, 0x7a, 0x8b, 0xa6, 0x26, 0xd8, 0xc7, 0x95, 0x2e, 0xfa, 0x1a,
	0xac, 0x01, 0xe1, 0x48, 0xa9, 0xc7, 0xf8, 0xc2, 0x71, 0x76, 0x8d, 0x3e, 0x1d, 0x7d, 0x4f, 0x46,
	0xb7, 0x51, 0xab, 0x10, 0xbd, 0xf7, 0x3d, 0xf5, 0x7f, 0x44, 0x4f, 0xa1, 0xae, 0xae, 0x03, 0xdd,
	0x46, 0xd9, 0x3d, 0xac, 0xdb, 0x28, 0xbf, 0x3a, 0x0e, 0x64, 0xa2, 0x5d, 0xa7, 0x24, 0x91, 0xe8,
	0x65, 0x0c, 0x75, 0x45, 0xbe, 0xce, 0x55, 0x76, 0xd5, 0xe8, 0x5c, 0xe5, 0xb7, 0x8b, 0x6e, 0xaa,
	0x5b, 0xd6, 0xd4, 0x57, 0x50, 0x13, 0x7a, 0x40, 0x6a, 0x67, 0xcc, 0x17, 0x91, 0xd3, 0x36, 0x3b,
	0x75, 0x8a, 0x1d, 0x99, 0x62, 0x0b, 0x15, 0x59, 0x41, 0xd7, 0x15, 0x68, 0x8a, 0x65, 0x9f, 0x87,
	0x83, 0xcc, 0xf8, 0x43, 0x07, 0xa6, 0x88, 0x99, 0x7b, 0xe8, 0x6f, 0x92, 0x7e, 0x20, 0x93, 0xde,
	0x45, 0x07, 0x85, 0xa4, 0x0f, 0xe6, 0xb9, 0x5c, 0x57, 0xb0, 0xad, 0x24, 0x95, 0x1f, 0x44, 0x4d,
	0xd3, 0x9c, 0x71, 0x90, 0xb4, 0x66, 0xe7, 0xe0, 0x7d, 0x99, 0xed, 0x43, 0xb7, 0x63, 0xde, 0xc5,
	0x1e, 0xbd, 0x5d, 0x9f, 0xf4, 0x9e, 0x70, 0x1e, 0x09, 0x0e, 0x7f, 0x00, 0x54, 0x3c, 0xed, 0x68,
	0x6f, 0x21, 0x41, 0xf3, 0x18, 0x70, 0x8c, 0x45, 0xb9, 0x47, 0xb2, 0x80, 0x2e, 0x5a, 0xba, 0x00,
	0xd1, 0xb5, 0x52, 0xe0, 0x0b, 0x77, 0xed, 0xfc, 0xc3, 0xae, 0xb7, 0x95, 0x1a, 0xf3, 0x79, 0xd3,
	0x42, 0x36, 0xf4, 0x6d, 0x2a, 0x40, 0x77, 0xdd, 0x5d, 0xbe, 0xeb, 0xe7, 0xd0, 0xc8, 0x8d, 0xb7,
	0x24, 0x25, 0x6d, 0x43, 0xda, 0xb6, 0xd9, 0xa9, 0x0b, 0xb8, 0x27, 0x0b, 0x78, 0x17, 0xdd, 0x5d,
	0xa2, 0x80, 0x6f, 0xea, 0xf2, 0x0f, 0xf1, 0xfd, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94, 0x56,
	0x34, 0xdf, 0x48, 0x0f, 0x00, 0x00,
}
