// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gatewayNetwork.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Request the gateway networks defined in the system.
type ListGatewayNetworksRequest struct {
	// Max number of gateway networks to return in the result-set.
	Limit int32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int32 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// When provided, the given string will be used to search on
	// Name.
	Search string `protobuf:"bytes,3,opt,name=search" json:"search,omitempty"`
}

func (m *ListGatewayNetworksRequest) Reset()                    { *m = ListGatewayNetworksRequest{} }
func (m *ListGatewayNetworksRequest) String() string            { return proto.CompactTextString(m) }
func (*ListGatewayNetworksRequest) ProtoMessage()               {}
func (*ListGatewayNetworksRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *ListGatewayNetworksRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListGatewayNetworksRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListGatewayNetworksRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

// Request the gateway network information.
type GatewayNetworkRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GatewayNetworkRequest) Reset()                    { *m = GatewayNetworkRequest{} }
func (m *GatewayNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*GatewayNetworkRequest) ProtoMessage()               {}
func (*GatewayNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *GatewayNetworkRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetGatewayNetworkResponse struct {
	// ID of the Gateway Network.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// When the gateway network was created.
	CreatedAt string `protobuf:"bytes,2,opt,name=createdAt" json:"createdAt,omitempty"`
	// When the gateway network was last updated.
	UpdatedAt string `protobuf:"bytes,3,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// Gateway Network name.
	Name string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	// Tags with specification data.
	Tags []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	// Price of the gateway network.
	Price int64 `protobuf:"varint,6,opt,name=price" json:"price,omitempty"`
	// Is the network private or not.
	PrivateNetwork bool `protobuf:"varint,7,opt,name=privateNetwork" json:"privateNetwork,omitempty"`
	// Organization the gateway network belongs to.
	OrganizationID int64 `protobuf:"varint,8,opt,name=organizationID" json:"organizationID,omitempty"`
}

func (m *GetGatewayNetworkResponse) Reset()                    { *m = GetGatewayNetworkResponse{} }
func (m *GetGatewayNetworkResponse) String() string            { return proto.CompactTextString(m) }
func (*GetGatewayNetworkResponse) ProtoMessage()               {}
func (*GetGatewayNetworkResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *GetGatewayNetworkResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetGatewayNetworkResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetGatewayNetworkResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetGatewayNetworkResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetGatewayNetworkResponse) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetGatewayNetworkResponse) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetGatewayNetworkResponse) GetPrivateNetwork() bool {
	if m != nil {
		return m.PrivateNetwork
	}
	return false
}

func (m *GetGatewayNetworkResponse) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

// Add a new organization.
type CreateGatewayNetworkRequest struct {
	// Gateway network name.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Tags with specification data.
	Tags []string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	// Price of the gateway network.
	Price int64 `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	// Is the network private or not.
	PrivateNetwork bool `protobuf:"varint,4,opt,name=privateNetwork" json:"privateNetwork,omitempty"`
	// Organization the gateway network belongs to.
	OrganizationID int64 `protobuf:"varint,5,opt,name=organizationID" json:"organizationID,omitempty"`
}

func (m *CreateGatewayNetworkRequest) Reset()                    { *m = CreateGatewayNetworkRequest{} }
func (m *CreateGatewayNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateGatewayNetworkRequest) ProtoMessage()               {}
func (*CreateGatewayNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *CreateGatewayNetworkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGatewayNetworkRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CreateGatewayNetworkRequest) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateGatewayNetworkRequest) GetPrivateNetwork() bool {
	if m != nil {
		return m.PrivateNetwork
	}
	return false
}

func (m *CreateGatewayNetworkRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

type CreateGatewayNetworkResponse struct {
	// ID of the gateway network.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateGatewayNetworkResponse) Reset()                    { *m = CreateGatewayNetworkResponse{} }
func (m *CreateGatewayNetworkResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateGatewayNetworkResponse) ProtoMessage()               {}
func (*CreateGatewayNetworkResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *CreateGatewayNetworkResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Update existing gateway network.
type UpdateGatewayNetworkRequest struct {
	// The ID of the gateway network to be updated.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The new name.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Tags with specification data.
	Tags []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	// Price of the gateway network.
	Price int64 `protobuf:"varint,4,opt,name=price" json:"price,omitempty"`
	// Is the network private or not.
	PrivateNetwork bool `protobuf:"varint,5,opt,name=privateNetwork" json:"privateNetwork,omitempty"`
	// Organization the gateway network belongs to.
	OrganizationID int64 `protobuf:"varint,6,opt,name=organizationID" json:"organizationID,omitempty"`
}

func (m *UpdateGatewayNetworkRequest) Reset()                    { *m = UpdateGatewayNetworkRequest{} }
func (m *UpdateGatewayNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateGatewayNetworkRequest) ProtoMessage()               {}
func (*UpdateGatewayNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *UpdateGatewayNetworkRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateGatewayNetworkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateGatewayNetworkRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UpdateGatewayNetworkRequest) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdateGatewayNetworkRequest) GetPrivateNetwork() bool {
	if m != nil {
		return m.PrivateNetwork
	}
	return false
}

func (m *UpdateGatewayNetworkRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

type ListGatewayNetworksResponse struct {
	TotalCount int32                        `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	Result     []*GetGatewayNetworkResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListGatewayNetworksResponse) Reset()                    { *m = ListGatewayNetworksResponse{} }
func (m *ListGatewayNetworksResponse) String() string            { return proto.CompactTextString(m) }
func (*ListGatewayNetworksResponse) ProtoMessage()               {}
func (*ListGatewayNetworksResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *ListGatewayNetworksResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListGatewayNetworksResponse) GetResult() []*GetGatewayNetworkResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type GatewayNetworkEmptyResponse struct {
}

func (m *GatewayNetworkEmptyResponse) Reset()                    { *m = GatewayNetworkEmptyResponse{} }
func (m *GatewayNetworkEmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*GatewayNetworkEmptyResponse) ProtoMessage()               {}
func (*GatewayNetworkEmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

type GatewayNetworkGatewayRequest struct {
	// The gateway network id.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Hex encoded gateway MAC.
	GatewayMAC string `protobuf:"bytes,2,opt,name=gatewayMAC" json:"gatewayMAC,omitempty"`
}

func (m *GatewayNetworkGatewayRequest) Reset()                    { *m = GatewayNetworkGatewayRequest{} }
func (m *GatewayNetworkGatewayRequest) String() string            { return proto.CompactTextString(m) }
func (*GatewayNetworkGatewayRequest) ProtoMessage()               {}
func (*GatewayNetworkGatewayRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *GatewayNetworkGatewayRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GatewayNetworkGatewayRequest) GetGatewayMAC() string {
	if m != nil {
		return m.GatewayMAC
	}
	return ""
}

type DeleteGatewayNetworkGatewayRequest struct {
	// The gateway network id.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Hex encoded gateway MAC.
	GatewayMAC string `protobuf:"bytes,2,opt,name=gatewayMAC" json:"gatewayMAC,omitempty"`
}

func (m *DeleteGatewayNetworkGatewayRequest) Reset()         { *m = DeleteGatewayNetworkGatewayRequest{} }
func (m *DeleteGatewayNetworkGatewayRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGatewayNetworkGatewayRequest) ProtoMessage()    {}
func (*DeleteGatewayNetworkGatewayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{9}
}

func (m *DeleteGatewayNetworkGatewayRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteGatewayNetworkGatewayRequest) GetGatewayMAC() string {
	if m != nil {
		return m.GatewayMAC
	}
	return ""
}

// Request the gateways in a gateway network.
type ListGatewayNetworkGatewaysRequest struct {
	// The gateway network id.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Max number of gateways to return in the result-set.
	Limit int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int32 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *ListGatewayNetworkGatewaysRequest) Reset()         { *m = ListGatewayNetworkGatewaysRequest{} }
func (m *ListGatewayNetworkGatewaysRequest) String() string { return proto.CompactTextString(m) }
func (*ListGatewayNetworkGatewaysRequest) ProtoMessage()    {}
func (*ListGatewayNetworkGatewaysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{10}
}

func (m *ListGatewayNetworkGatewaysRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListGatewayNetworkGatewaysRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListGatewayNetworkGatewaysRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetGatewayNetworkGatewayRequest struct {
	// ID of the gateway network.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Hex encoded MAC of the gateway.
	GatewayMAC string `protobuf:"bytes,2,opt,name=gatewayMAC" json:"gatewayMAC,omitempty"`
}

func (m *GetGatewayNetworkGatewayRequest) Reset()         { *m = GetGatewayNetworkGatewayRequest{} }
func (m *GetGatewayNetworkGatewayRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayNetworkGatewayRequest) ProtoMessage()    {}
func (*GetGatewayNetworkGatewayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{11}
}

func (m *GetGatewayNetworkGatewayRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetGatewayNetworkGatewayRequest) GetGatewayMAC() string {
	if m != nil {
		return m.GatewayMAC
	}
	return ""
}

// Response for a gateway in the gateway network
type GetGatewayNetworkGatewayResponse struct {
	// Hex encoded mac of the gateway.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	// Name of the gateway.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// When the gatewayy was created.
	CreatedAt string `protobuf:"bytes,3,opt,name=createdAt" json:"createdAt,omitempty"`
	// When the gateway was last updated.
	UpdatedAt string `protobuf:"bytes,4,opt,name=updatedAt" json:"updatedAt,omitempty"`
}

func (m *GetGatewayNetworkGatewayResponse) Reset()         { *m = GetGatewayNetworkGatewayResponse{} }
func (m *GetGatewayNetworkGatewayResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayNetworkGatewayResponse) ProtoMessage()    {}
func (*GetGatewayNetworkGatewayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{12}
}

func (m *GetGatewayNetworkGatewayResponse) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *GetGatewayNetworkGatewayResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetGatewayNetworkGatewayResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetGatewayNetworkGatewayResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// Response for the gateways in a gateway network.
type ListGatewayNetworkGatewaysResponse struct {
	// The total number of gateways in the gateway network.
	TotalCount int32 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// The gateways in the requested limit, offset range.
	Result []*GetGatewayNetworkGatewayResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListGatewayNetworkGatewaysResponse) Reset()         { *m = ListGatewayNetworkGatewaysResponse{} }
func (m *ListGatewayNetworkGatewaysResponse) String() string { return proto.CompactTextString(m) }
func (*ListGatewayNetworkGatewaysResponse) ProtoMessage()    {}
func (*ListGatewayNetworkGatewaysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{13}
}

func (m *ListGatewayNetworkGatewaysResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListGatewayNetworkGatewaysResponse) GetResult() []*GetGatewayNetworkGatewayResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*ListGatewayNetworksRequest)(nil), "api.ListGatewayNetworksRequest")
	proto.RegisterType((*GatewayNetworkRequest)(nil), "api.GatewayNetworkRequest")
	proto.RegisterType((*GetGatewayNetworkResponse)(nil), "api.GetGatewayNetworkResponse")
	proto.RegisterType((*CreateGatewayNetworkRequest)(nil), "api.CreateGatewayNetworkRequest")
	proto.RegisterType((*CreateGatewayNetworkResponse)(nil), "api.CreateGatewayNetworkResponse")
	proto.RegisterType((*UpdateGatewayNetworkRequest)(nil), "api.UpdateGatewayNetworkRequest")
	proto.RegisterType((*ListGatewayNetworksResponse)(nil), "api.ListGatewayNetworksResponse")
	proto.RegisterType((*GatewayNetworkEmptyResponse)(nil), "api.GatewayNetworkEmptyResponse")
	proto.RegisterType((*GatewayNetworkGatewayRequest)(nil), "api.GatewayNetworkGatewayRequest")
	proto.RegisterType((*DeleteGatewayNetworkGatewayRequest)(nil), "api.DeleteGatewayNetworkGatewayRequest")
	proto.RegisterType((*ListGatewayNetworkGatewaysRequest)(nil), "api.ListGatewayNetworkGatewaysRequest")
	proto.RegisterType((*GetGatewayNetworkGatewayRequest)(nil), "api.GetGatewayNetworkGatewayRequest")
	proto.RegisterType((*GetGatewayNetworkGatewayResponse)(nil), "api.GetGatewayNetworkGatewayResponse")
	proto.RegisterType((*ListGatewayNetworkGatewaysResponse)(nil), "api.ListGatewayNetworkGatewaysResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GatewayNetwork service

type GatewayNetworkClient interface {
	// Get gateway network list.
	List(ctx context.Context, in *ListGatewayNetworksRequest, opts ...grpc.CallOption) (*ListGatewayNetworksResponse, error)
	// Get data for a particular gateway network.
	Get(ctx context.Context, in *GatewayNetworkRequest, opts ...grpc.CallOption) (*GetGatewayNetworkResponse, error)
	// Create a new gateway network.
	Create(ctx context.Context, in *CreateGatewayNetworkRequest, opts ...grpc.CallOption) (*CreateGatewayNetworkResponse, error)
	// Update an existing gateway network.
	Update(ctx context.Context, in *UpdateGatewayNetworkRequest, opts ...grpc.CallOption) (*GatewayNetworkEmptyResponse, error)
	// Delete a gateway network.
	Delete(ctx context.Context, in *GatewayNetworkRequest, opts ...grpc.CallOption) (*GatewayNetworkEmptyResponse, error)
	// Get gateway networks's gateway list.
	ListGateways(ctx context.Context, in *ListGatewayNetworkGatewaysRequest, opts ...grpc.CallOption) (*ListGatewayNetworkGatewaysResponse, error)
	// Get data for a particular gateway network gateway.
	GetGateway(ctx context.Context, in *GetGatewayNetworkGatewayRequest, opts ...grpc.CallOption) (*GetGatewayNetworkGatewayResponse, error)
	// Add a new gateway to a gateway network
	AddGateway(ctx context.Context, in *GatewayNetworkGatewayRequest, opts ...grpc.CallOption) (*GatewayNetworkEmptyResponse, error)
	// Delete a gateway from a gateway network.
	DeleteGateway(ctx context.Context, in *DeleteGatewayNetworkGatewayRequest, opts ...grpc.CallOption) (*GatewayNetworkEmptyResponse, error)
}

type gatewayNetworkClient struct {
	cc *grpc.ClientConn
}

func NewGatewayNetworkClient(cc *grpc.ClientConn) GatewayNetworkClient {
	return &gatewayNetworkClient{cc}
}

func (c *gatewayNetworkClient) List(ctx context.Context, in *ListGatewayNetworksRequest, opts ...grpc.CallOption) (*ListGatewayNetworksResponse, error) {
	out := new(ListGatewayNetworksResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkClient) Get(ctx context.Context, in *GatewayNetworkRequest, opts ...grpc.CallOption) (*GetGatewayNetworkResponse, error) {
	out := new(GetGatewayNetworkResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkClient) Create(ctx context.Context, in *CreateGatewayNetworkRequest, opts ...grpc.CallOption) (*CreateGatewayNetworkResponse, error) {
	out := new(CreateGatewayNetworkResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkClient) Update(ctx context.Context, in *UpdateGatewayNetworkRequest, opts ...grpc.CallOption) (*GatewayNetworkEmptyResponse, error) {
	out := new(GatewayNetworkEmptyResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkClient) Delete(ctx context.Context, in *GatewayNetworkRequest, opts ...grpc.CallOption) (*GatewayNetworkEmptyResponse, error) {
	out := new(GatewayNetworkEmptyResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkClient) ListGateways(ctx context.Context, in *ListGatewayNetworkGatewaysRequest, opts ...grpc.CallOption) (*ListGatewayNetworkGatewaysResponse, error) {
	out := new(ListGatewayNetworkGatewaysResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/ListGateways", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkClient) GetGateway(ctx context.Context, in *GetGatewayNetworkGatewayRequest, opts ...grpc.CallOption) (*GetGatewayNetworkGatewayResponse, error) {
	out := new(GetGatewayNetworkGatewayResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/GetGateway", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkClient) AddGateway(ctx context.Context, in *GatewayNetworkGatewayRequest, opts ...grpc.CallOption) (*GatewayNetworkEmptyResponse, error) {
	out := new(GatewayNetworkEmptyResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/AddGateway", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkClient) DeleteGateway(ctx context.Context, in *DeleteGatewayNetworkGatewayRequest, opts ...grpc.CallOption) (*GatewayNetworkEmptyResponse, error) {
	out := new(GatewayNetworkEmptyResponse)
	err := grpc.Invoke(ctx, "/api.GatewayNetwork/DeleteGateway", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GatewayNetwork service

type GatewayNetworkServer interface {
	// Get gateway network list.
	List(context.Context, *ListGatewayNetworksRequest) (*ListGatewayNetworksResponse, error)
	// Get data for a particular gateway network.
	Get(context.Context, *GatewayNetworkRequest) (*GetGatewayNetworkResponse, error)
	// Create a new gateway network.
	Create(context.Context, *CreateGatewayNetworkRequest) (*CreateGatewayNetworkResponse, error)
	// Update an existing gateway network.
	Update(context.Context, *UpdateGatewayNetworkRequest) (*GatewayNetworkEmptyResponse, error)
	// Delete a gateway network.
	Delete(context.Context, *GatewayNetworkRequest) (*GatewayNetworkEmptyResponse, error)
	// Get gateway networks's gateway list.
	ListGateways(context.Context, *ListGatewayNetworkGatewaysRequest) (*ListGatewayNetworkGatewaysResponse, error)
	// Get data for a particular gateway network gateway.
	GetGateway(context.Context, *GetGatewayNetworkGatewayRequest) (*GetGatewayNetworkGatewayResponse, error)
	// Add a new gateway to a gateway network
	AddGateway(context.Context, *GatewayNetworkGatewayRequest) (*GatewayNetworkEmptyResponse, error)
	// Delete a gateway from a gateway network.
	DeleteGateway(context.Context, *DeleteGatewayNetworkGatewayRequest) (*GatewayNetworkEmptyResponse, error)
}

func RegisterGatewayNetworkServer(s *grpc.Server, srv GatewayNetworkServer) {
	s.RegisterService(&_GatewayNetwork_serviceDesc, srv)
}

func _GatewayNetwork_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewayNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).List(ctx, req.(*ListGatewayNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetwork_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).Get(ctx, req.(*GatewayNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetwork_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGatewayNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).Create(ctx, req.(*CreateGatewayNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetwork_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGatewayNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).Update(ctx, req.(*UpdateGatewayNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetwork_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).Delete(ctx, req.(*GatewayNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetwork_ListGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewayNetworkGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).ListGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/ListGateways",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).ListGateways(ctx, req.(*ListGatewayNetworkGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetwork_GetGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayNetworkGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).GetGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/GetGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).GetGateway(ctx, req.(*GetGatewayNetworkGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetwork_AddGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayNetworkGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).AddGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/AddGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).AddGateway(ctx, req.(*GatewayNetworkGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetwork_DeleteGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayNetworkGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServer).DeleteGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayNetwork/DeleteGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServer).DeleteGateway(ctx, req.(*DeleteGatewayNetworkGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GatewayNetwork",
	HandlerType: (*GatewayNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _GatewayNetwork_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GatewayNetwork_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _GatewayNetwork_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _GatewayNetwork_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GatewayNetwork_Delete_Handler,
		},
		{
			MethodName: "ListGateways",
			Handler:    _GatewayNetwork_ListGateways_Handler,
		},
		{
			MethodName: "GetGateway",
			Handler:    _GatewayNetwork_GetGateway_Handler,
		},
		{
			MethodName: "AddGateway",
			Handler:    _GatewayNetwork_AddGateway_Handler,
		},
		{
			MethodName: "DeleteGateway",
			Handler:    _GatewayNetwork_DeleteGateway_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gatewayNetwork.proto",
}

func init() { proto.RegisterFile("gatewayNetwork.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0xd6, 0xc6, 0x89, 0x4f, 0x3b, 0xe7, 0x9c, 0xea, 0x68, 0xd5, 0x53, 0xb9, 0x4e, 0x48, 0x93,
	0x55, 0x69, 0xab, 0x48, 0x24, 0xa2, 0x48, 0x20, 0x21, 0x71, 0x51, 0xb5, 0xa8, 0x42, 0x82, 0x4a,
	0x44, 0xf0, 0x00, 0xdb, 0x78, 0x1b, 0x56, 0x24, 0xb6, 0xb1, 0x37, 0x54, 0xa5, 0xaa, 0x84, 0x80,
	0x3b, 0xee, 0xe8, 0x63, 0xf0, 0x08, 0x3c, 0x06, 0xaf, 0xc0, 0x15, 0xf7, 0xdc, 0x23, 0xaf, 0xd7,
	0x4d, 0xec, 0xae, 0x7f, 0x50, 0xef, 0xbc, 0xb3, 0x93, 0x99, 0x6f, 0xbe, 0x99, 0xf9, 0x36, 0xb0,
	0x3a, 0xa6, 0x82, 0x9d, 0xd2, 0xb3, 0x23, 0x26, 0x4e, 0xbd, 0xe0, 0x75, 0xdf, 0x0f, 0x3c, 0xe1,
	0x61, 0x83, 0xfa, 0xdc, 0x6e, 0x8d, 0x3d, 0x6f, 0x3c, 0x61, 0x03, 0xea, 0xf3, 0x01, 0x75, 0x5d,
	0x4f, 0x50, 0xc1, 0x3d, 0x37, 0x8c, 0x5d, 0xc8, 0x31, 0xd8, 0x4f, 0x79, 0x28, 0x0e, 0x53, 0x3f,
	0x0f, 0x87, 0xec, 0xcd, 0x8c, 0x85, 0x02, 0xaf, 0x42, 0x63, 0xc2, 0xa7, 0x5c, 0x58, 0xa8, 0x83,
	0x76, 0x1a, 0xc3, 0xf8, 0x80, 0xd7, 0xc0, 0xf4, 0x4e, 0x4e, 0x42, 0x26, 0xac, 0x9a, 0x34, 0xab,
	0x53, 0x64, 0x0f, 0x19, 0x0d, 0x46, 0xaf, 0x2c, 0xa3, 0x83, 0x76, 0x96, 0x87, 0xea, 0x44, 0xb6,
	0xe1, 0xff, 0x74, 0xfc, 0x24, 0xfc, 0x0a, 0xd4, 0xb8, 0x23, 0x63, 0x1b, 0xc3, 0x1a, 0x77, 0xc8,
	0x2f, 0x04, 0xeb, 0x87, 0x4c, 0x64, 0x9d, 0x43, 0xdf, 0x73, 0x43, 0x96, 0xf5, 0xc6, 0x2d, 0x58,
	0x1e, 0x05, 0x8c, 0x0a, 0xe6, 0xec, 0xc5, 0x48, 0x96, 0x87, 0x73, 0x43, 0x74, 0x3b, 0xf3, 0x1d,
	0x75, 0x1b, 0xe3, 0x99, 0x1b, 0x30, 0x86, 0xba, 0x4b, 0xa7, 0xcc, 0xaa, 0xcb, 0x0b, 0xf9, 0x1d,
	0xd9, 0x04, 0x1d, 0x87, 0x56, 0xa3, 0x63, 0x44, 0xb6, 0xe8, 0x3b, 0x22, 0xc0, 0x0f, 0xf8, 0x88,
	0x59, 0xa6, 0x4c, 0x1b, 0x1f, 0xf0, 0x16, 0xac, 0xf8, 0x01, 0x7f, 0x4b, 0x05, 0x53, 0x18, 0xad,
	0xbf, 0x3a, 0x68, 0x67, 0x69, 0x98, 0xb1, 0x46, 0x7e, 0x5e, 0x30, 0xa6, 0x2e, 0x7f, 0x27, 0x39,
	0x7f, 0x72, 0x60, 0x2d, 0xc9, 0x30, 0x19, 0x2b, 0xf9, 0x8a, 0xa0, 0xb9, 0x2f, 0x91, 0xeb, 0x79,
	0x4a, 0xd0, 0x22, 0x0d, 0xda, 0x9a, 0x0e, 0xad, 0x51, 0x8c, 0xb6, 0x5e, 0x11, 0x6d, 0x43, 0x8b,
	0xb6, 0x0f, 0x2d, 0x3d, 0x58, 0x7d, 0x9f, 0xc8, 0x37, 0x04, 0xcd, 0x97, 0x92, 0xf9, 0x4a, 0x53,
	0x70, 0x55, 0x6d, 0x4d, 0x53, 0xad, 0xa1, 0xab, 0xb6, 0x5e, 0x5c, 0x6d, 0xa3, 0x62, 0xb5, 0xa6,
	0xb6, 0xda, 0x19, 0x34, 0xb5, 0x0b, 0xa2, 0x8a, 0x6d, 0x03, 0x08, 0x4f, 0xd0, 0xc9, 0xbe, 0x37,
	0x73, 0x93, 0x35, 0x59, 0xb0, 0xe0, 0xfb, 0x60, 0x06, 0x2c, 0x9c, 0x4d, 0x84, 0x6c, 0xd4, 0xdf,
	0xbb, 0xed, 0x3e, 0xf5, 0x79, 0x3f, 0x77, 0xc8, 0x87, 0xca, 0x9b, 0xdc, 0x82, 0x66, 0xda, 0xe3,
	0xf1, 0xd4, 0x17, 0x67, 0x89, 0x1b, 0x39, 0x82, 0x56, 0xfa, 0x5a, 0x9d, 0xf2, 0x38, 0x6d, 0x03,
	0x28, 0x85, 0x78, 0xb6, 0xb7, 0xaf, 0x98, 0x5d, 0xb0, 0x90, 0x17, 0x40, 0x0e, 0xd8, 0x84, 0x65,
	0x5b, 0x74, 0xc3, 0xa8, 0x14, 0xba, 0xd7, 0xb9, 0x53, 0xa7, 0x30, 0x2f, 0xe8, 0x95, 0xe6, 0xd4,
	0xf4, 0x9a, 0x63, 0x2c, 0x6a, 0x0e, 0x79, 0x0e, 0x1b, 0xd7, 0xc8, 0xbc, 0x21, 0xea, 0x4f, 0x08,
	0x3a, 0xf9, 0x31, 0x55, 0xdf, 0xff, 0x03, 0x63, 0x4a, 0x47, 0x6a, 0x23, 0xa3, 0x4f, 0xed, 0xd8,
	0xa6, 0x24, 0xca, 0x28, 0x94, 0xa8, 0x7a, 0x46, 0xa2, 0xc8, 0x47, 0x04, 0xa4, 0x88, 0xbd, 0x8a,
	0x03, 0xf8, 0x28, 0x33, 0x80, 0xb7, 0xf5, 0x03, 0x98, 0xa9, 0x2f, 0x99, 0xc3, 0xdd, 0x9f, 0x4b,
	0xb0, 0x92, 0xf6, 0xc4, 0x63, 0xa8, 0x47, 0xb8, 0xf0, 0x86, 0x8c, 0x94, 0xff, 0x7a, 0xd8, 0x9d,
	0x7c, 0x07, 0x35, 0xc6, 0xad, 0x0f, 0xdf, 0x7f, 0x5c, 0xd6, 0xd6, 0xf0, 0xaa, 0x7c, 0x9d, 0x54,
	0x0f, 0x5c, 0xe5, 0x85, 0x1d, 0x30, 0x0e, 0x99, 0xc0, 0x76, 0x8c, 0x58, 0xa7, 0x1d, 0x76, 0xc9,
	0x3a, 0x91, 0xae, 0x4c, 0xd0, 0xc4, 0xeb, 0xba, 0x04, 0x83, 0x73, 0xee, 0x5c, 0x60, 0x17, 0xcc,
	0x58, 0xce, 0x70, 0x8c, 0xb7, 0x40, 0x88, 0xed, 0x6e, 0x81, 0x87, 0xca, 0xb8, 0x21, 0x33, 0xae,
	0x13, 0x6d, 0x49, 0x0f, 0x51, 0x0f, 0x07, 0x60, 0xc6, 0x6a, 0xa8, 0xf2, 0x15, 0x48, 0xa3, 0x62,
	0xb0, 0x48, 0x08, 0x36, 0x65, 0xba, 0xb6, 0x9d, 0x5f, 0x60, 0x94, 0x93, 0x83, 0x19, 0xaf, 0x77,
	0x21, 0x99, 0xe5, 0xd9, 0x14, 0x9d, 0xbd, 0x02, 0x3a, 0x3f, 0x23, 0xf8, 0x67, 0xa1, 0xe5, 0x21,
	0xde, 0xca, 0x99, 0x82, 0x8c, 0x0e, 0xd8, 0xdb, 0xa5, 0x7e, 0x0a, 0x44, 0x4f, 0x82, 0xd8, 0xc4,
	0x24, 0x17, 0x44, 0x62, 0x0c, 0xf1, 0x17, 0x04, 0x30, 0x9f, 0x0e, 0xbc, 0x59, 0x32, 0xfc, 0x31,
	0x92, 0x6a, 0x2b, 0x42, 0x1e, 0x48, 0x1c, 0x77, 0xf1, 0xa0, 0x1c, 0xc7, 0xe0, 0x7c, 0xae, 0x2f,
	0x17, 0xf8, 0x3d, 0x02, 0xd8, 0x73, 0x9c, 0x04, 0x54, 0x57, 0x43, 0x7b, 0x06, 0x51, 0x79, 0x67,
	0xee, 0x48, 0x30, 0xdb, 0xa4, 0x02, 0x29, 0xd1, 0x40, 0x5c, 0x22, 0xf8, 0x37, 0x25, 0xf8, 0x38,
	0xa6, 0xbf, 0xfc, 0x11, 0xa8, 0x80, 0x45, 0x11, 0xd3, 0xfb, 0x53, 0x62, 0x8e, 0x4d, 0xf9, 0x9f,
	0xf4, 0xde, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x2e, 0x93, 0xaa, 0xce, 0x0a, 0x00, 0x00,
}
