// Code generated by protoc-gen-go. DO NOT EDIT.
// source: organization.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Request the organizations defined in the system.
type ListOrganizationRequest struct {
	// Max number of organizations to return in the result-set.
	Limit int32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int32 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// When provided, the given string will be used to search on
	// displayName.
	Search string `protobuf:"bytes,3,opt,name=search" json:"search,omitempty"`
}

func (m *ListOrganizationRequest) Reset()                    { *m = ListOrganizationRequest{} }
func (m *ListOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*ListOrganizationRequest) ProtoMessage()               {}
func (*ListOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *ListOrganizationRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListOrganizationRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListOrganizationRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

// Request the user information.
type OrganizationRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *OrganizationRequest) Reset()                    { *m = OrganizationRequest{} }
func (m *OrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationRequest) ProtoMessage()               {}
func (*OrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *OrganizationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetOrganizationResponse struct {
	// ID of the user.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Organization name.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Organization display name.
	DisplayName string `protobuf:"bytes,3,opt,name=displayName" json:"displayName,omitempty"`
	// Can the organization create and "own" Gateways?
	CanHaveGateways bool `protobuf:"varint,4,opt,name=canHaveGateways" json:"canHaveGateways,omitempty"`
	// When the user was created.
	CreatedAt string `protobuf:"bytes,5,opt,name=createdAt" json:"createdAt,omitempty"`
	// When the user was last updated (excludes changes in application access).
	UpdatedAt string `protobuf:"bytes,6,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// Organization Number.
	OrgNr string `protobuf:"bytes,7,opt,name=orgNr" json:"orgNr,omitempty"`
}

func (m *GetOrganizationResponse) Reset()                    { *m = GetOrganizationResponse{} }
func (m *GetOrganizationResponse) String() string            { return proto.CompactTextString(m) }
func (*GetOrganizationResponse) ProtoMessage()               {}
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *GetOrganizationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetOrganizationResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetOrganizationResponse) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *GetOrganizationResponse) GetCanHaveGateways() bool {
	if m != nil {
		return m.CanHaveGateways
	}
	return false
}

func (m *GetOrganizationResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetOrganizationResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetOrganizationResponse) GetOrgNr() string {
	if m != nil {
		return m.OrgNr
	}
	return ""
}

// Add a new organization.
type CreateOrganizationRequest struct {
	// Organization name.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Organization display name.
	DisplayName string `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	// Can the organization create and "own" Gateways?
	CanHaveGateways bool `protobuf:"varint,3,opt,name=canHaveGateways" json:"canHaveGateways,omitempty"`
	// The Organization number
	OrgNr string `protobuf:"bytes,4,opt,name=orgNr" json:"orgNr,omitempty"`
}

func (m *CreateOrganizationRequest) Reset()                    { *m = CreateOrganizationRequest{} }
func (m *CreateOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateOrganizationRequest) ProtoMessage()               {}
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *CreateOrganizationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOrganizationRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CreateOrganizationRequest) GetCanHaveGateways() bool {
	if m != nil {
		return m.CanHaveGateways
	}
	return false
}

func (m *CreateOrganizationRequest) GetOrgNr() string {
	if m != nil {
		return m.OrgNr
	}
	return ""
}

type CreateOrganizationResponse struct {
	// ID of the organization.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateOrganizationResponse) Reset()                    { *m = CreateOrganizationResponse{} }
func (m *CreateOrganizationResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateOrganizationResponse) ProtoMessage()               {}
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *CreateOrganizationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Not quite the AddOrganizationRequest.
type UpdateOrganizationRequest struct {
	// The ID of the organization to be updated.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The new name.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// The new display name.
	DisplayName string `protobuf:"bytes,3,opt,name=displayName" json:"displayName,omitempty"`
	// Can the organization create and "own" Gateways?
	CanHaveGateways bool `protobuf:"varint,4,opt,name=canHaveGateways" json:"canHaveGateways,omitempty"`
	// The new org number
	OrgNr string `protobuf:"bytes,5,opt,name=orgNr" json:"orgNr,omitempty"`
}

func (m *UpdateOrganizationRequest) Reset()                    { *m = UpdateOrganizationRequest{} }
func (m *UpdateOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateOrganizationRequest) ProtoMessage()               {}
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *UpdateOrganizationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateOrganizationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateOrganizationRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UpdateOrganizationRequest) GetCanHaveGateways() bool {
	if m != nil {
		return m.CanHaveGateways
	}
	return false
}

func (m *UpdateOrganizationRequest) GetOrgNr() string {
	if m != nil {
		return m.OrgNr
	}
	return ""
}

type ListOrganizationResponse struct {
	TotalCount int32                      `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	Result     []*GetOrganizationResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListOrganizationResponse) Reset()                    { *m = ListOrganizationResponse{} }
func (m *ListOrganizationResponse) String() string            { return proto.CompactTextString(m) }
func (*ListOrganizationResponse) ProtoMessage()               {}
func (*ListOrganizationResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *ListOrganizationResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListOrganizationResponse) GetResult() []*GetOrganizationResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type OrganizationEmptyResponse struct {
}

func (m *OrganizationEmptyResponse) Reset()                    { *m = OrganizationEmptyResponse{} }
func (m *OrganizationEmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*OrganizationEmptyResponse) ProtoMessage()               {}
func (*OrganizationEmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

type OrganizationUserRequest struct {
	// The organization id.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The user's id.
	UserID int64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	// The user's admin status for the organization
	IsAdmin bool `protobuf:"varint,3,opt,name=isAdmin" json:"isAdmin,omitempty"`
}

func (m *OrganizationUserRequest) Reset()                    { *m = OrganizationUserRequest{} }
func (m *OrganizationUserRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationUserRequest) ProtoMessage()               {}
func (*OrganizationUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *OrganizationUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrganizationUserRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *OrganizationUserRequest) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type DeleteOrganizationUserRequest struct {
	// The organization id.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The user's id.
	UserID int64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *DeleteOrganizationUserRequest) Reset()                    { *m = DeleteOrganizationUserRequest{} }
func (m *DeleteOrganizationUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteOrganizationUserRequest) ProtoMessage()               {}
func (*DeleteOrganizationUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{9} }

func (m *DeleteOrganizationUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteOrganizationUserRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

// Request the users in an organization.
type ListOrganizationUsersRequest struct {
	// The organization id.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Max number of users to return in the result-set.
	Limit int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int32 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *ListOrganizationUsersRequest) Reset()                    { *m = ListOrganizationUsersRequest{} }
func (m *ListOrganizationUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListOrganizationUsersRequest) ProtoMessage()               {}
func (*ListOrganizationUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{10} }

func (m *ListOrganizationUsersRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListOrganizationUsersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListOrganizationUsersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetOrganizationUserRequest struct {
	// ID of the organization.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// ID of the user.
	UserID int64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *GetOrganizationUserRequest) Reset()                    { *m = GetOrganizationUserRequest{} }
func (m *GetOrganizationUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrganizationUserRequest) ProtoMessage()               {}
func (*GetOrganizationUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{11} }

func (m *GetOrganizationUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetOrganizationUserRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

// Response for a user in the organization
type GetOrganizationUserResponse struct {
	// ID of the user.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Username of the user.
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	// If the user is a system admin, capable of creating other users.
	IsAdmin bool `protobuf:"varint,3,opt,name=isAdmin" json:"isAdmin,omitempty"`
	// When the user was created.
	CreatedAt string `protobuf:"bytes,4,opt,name=createdAt" json:"createdAt,omitempty"`
	// When the user was last updated (excludes changes in application access).
	UpdatedAt string `protobuf:"bytes,5,opt,name=updatedAt" json:"updatedAt,omitempty"`
}

func (m *GetOrganizationUserResponse) Reset()                    { *m = GetOrganizationUserResponse{} }
func (m *GetOrganizationUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetOrganizationUserResponse) ProtoMessage()               {}
func (*GetOrganizationUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{12} }

func (m *GetOrganizationUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetOrganizationUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetOrganizationUserResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *GetOrganizationUserResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetOrganizationUserResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// Response for the users in an organization.
type ListOrganizationUsersResponse struct {
	// The total number of users in the organization.
	TotalCount int32 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// The users in the requested limit, offset range.
	Result []*GetOrganizationUserResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListOrganizationUsersResponse) Reset()                    { *m = ListOrganizationUsersResponse{} }
func (m *ListOrganizationUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListOrganizationUsersResponse) ProtoMessage()               {}
func (*ListOrganizationUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{13} }

func (m *ListOrganizationUsersResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListOrganizationUsersResponse) GetResult() []*GetOrganizationUserResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*ListOrganizationRequest)(nil), "api.ListOrganizationRequest")
	proto.RegisterType((*OrganizationRequest)(nil), "api.OrganizationRequest")
	proto.RegisterType((*GetOrganizationResponse)(nil), "api.GetOrganizationResponse")
	proto.RegisterType((*CreateOrganizationRequest)(nil), "api.CreateOrganizationRequest")
	proto.RegisterType((*CreateOrganizationResponse)(nil), "api.CreateOrganizationResponse")
	proto.RegisterType((*UpdateOrganizationRequest)(nil), "api.UpdateOrganizationRequest")
	proto.RegisterType((*ListOrganizationResponse)(nil), "api.ListOrganizationResponse")
	proto.RegisterType((*OrganizationEmptyResponse)(nil), "api.OrganizationEmptyResponse")
	proto.RegisterType((*OrganizationUserRequest)(nil), "api.OrganizationUserRequest")
	proto.RegisterType((*DeleteOrganizationUserRequest)(nil), "api.DeleteOrganizationUserRequest")
	proto.RegisterType((*ListOrganizationUsersRequest)(nil), "api.ListOrganizationUsersRequest")
	proto.RegisterType((*GetOrganizationUserRequest)(nil), "api.GetOrganizationUserRequest")
	proto.RegisterType((*GetOrganizationUserResponse)(nil), "api.GetOrganizationUserResponse")
	proto.RegisterType((*ListOrganizationUsersResponse)(nil), "api.ListOrganizationUsersResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Organization service

type OrganizationClient interface {
	// Get organization list.
	List(ctx context.Context, in *ListOrganizationRequest, opts ...grpc.CallOption) (*ListOrganizationResponse, error)
	// Get data for a particular organization.
	Get(ctx context.Context, in *OrganizationRequest, opts ...grpc.CallOption) (*GetOrganizationResponse, error)
	// Create a new organization.
	Create(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error)
	// Update an existing organization.
	Update(ctx context.Context, in *UpdateOrganizationRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error)
	// Delete an organization.
	Delete(ctx context.Context, in *OrganizationRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error)
	// Get organization's user list.
	ListUsers(ctx context.Context, in *ListOrganizationUsersRequest, opts ...grpc.CallOption) (*ListOrganizationUsersResponse, error)
	// Get data for a particular organization user.
	GetUser(ctx context.Context, in *GetOrganizationUserRequest, opts ...grpc.CallOption) (*GetOrganizationUserResponse, error)
	// Add a new user to an organization.
	AddUser(ctx context.Context, in *OrganizationUserRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error)
	// Update a user in an organization.
	UpdateUser(ctx context.Context, in *OrganizationUserRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error)
	// Delete a user from an organization.
	DeleteUser(ctx context.Context, in *DeleteOrganizationUserRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error)
}

type organizationClient struct {
	cc *grpc.ClientConn
}

func NewOrganizationClient(cc *grpc.ClientConn) OrganizationClient {
	return &organizationClient{cc}
}

func (c *organizationClient) List(ctx context.Context, in *ListOrganizationRequest, opts ...grpc.CallOption) (*ListOrganizationResponse, error) {
	out := new(ListOrganizationResponse)
	err := grpc.Invoke(ctx, "/api.Organization/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) Get(ctx context.Context, in *OrganizationRequest, opts ...grpc.CallOption) (*GetOrganizationResponse, error) {
	out := new(GetOrganizationResponse)
	err := grpc.Invoke(ctx, "/api.Organization/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) Create(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error) {
	out := new(CreateOrganizationResponse)
	err := grpc.Invoke(ctx, "/api.Organization/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) Update(ctx context.Context, in *UpdateOrganizationRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error) {
	out := new(OrganizationEmptyResponse)
	err := grpc.Invoke(ctx, "/api.Organization/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) Delete(ctx context.Context, in *OrganizationRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error) {
	out := new(OrganizationEmptyResponse)
	err := grpc.Invoke(ctx, "/api.Organization/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) ListUsers(ctx context.Context, in *ListOrganizationUsersRequest, opts ...grpc.CallOption) (*ListOrganizationUsersResponse, error) {
	out := new(ListOrganizationUsersResponse)
	err := grpc.Invoke(ctx, "/api.Organization/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) GetUser(ctx context.Context, in *GetOrganizationUserRequest, opts ...grpc.CallOption) (*GetOrganizationUserResponse, error) {
	out := new(GetOrganizationUserResponse)
	err := grpc.Invoke(ctx, "/api.Organization/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) AddUser(ctx context.Context, in *OrganizationUserRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error) {
	out := new(OrganizationEmptyResponse)
	err := grpc.Invoke(ctx, "/api.Organization/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) UpdateUser(ctx context.Context, in *OrganizationUserRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error) {
	out := new(OrganizationEmptyResponse)
	err := grpc.Invoke(ctx, "/api.Organization/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) DeleteUser(ctx context.Context, in *DeleteOrganizationUserRequest, opts ...grpc.CallOption) (*OrganizationEmptyResponse, error) {
	out := new(OrganizationEmptyResponse)
	err := grpc.Invoke(ctx, "/api.Organization/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Organization service

type OrganizationServer interface {
	// Get organization list.
	List(context.Context, *ListOrganizationRequest) (*ListOrganizationResponse, error)
	// Get data for a particular organization.
	Get(context.Context, *OrganizationRequest) (*GetOrganizationResponse, error)
	// Create a new organization.
	Create(context.Context, *CreateOrganizationRequest) (*CreateOrganizationResponse, error)
	// Update an existing organization.
	Update(context.Context, *UpdateOrganizationRequest) (*OrganizationEmptyResponse, error)
	// Delete an organization.
	Delete(context.Context, *OrganizationRequest) (*OrganizationEmptyResponse, error)
	// Get organization's user list.
	ListUsers(context.Context, *ListOrganizationUsersRequest) (*ListOrganizationUsersResponse, error)
	// Get data for a particular organization user.
	GetUser(context.Context, *GetOrganizationUserRequest) (*GetOrganizationUserResponse, error)
	// Add a new user to an organization.
	AddUser(context.Context, *OrganizationUserRequest) (*OrganizationEmptyResponse, error)
	// Update a user in an organization.
	UpdateUser(context.Context, *OrganizationUserRequest) (*OrganizationEmptyResponse, error)
	// Delete a user from an organization.
	DeleteUser(context.Context, *DeleteOrganizationUserRequest) (*OrganizationEmptyResponse, error)
}

func RegisterOrganizationServer(s *grpc.Server, srv OrganizationServer) {
	s.RegisterService(&_Organization_serviceDesc, srv)
}

func _Organization_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).List(ctx, req.(*ListOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).Get(ctx, req.(*OrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).Create(ctx, req.(*CreateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).Update(ctx, req.(*UpdateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).Delete(ctx, req.(*OrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrganizationUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).ListUsers(ctx, req.(*ListOrganizationUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).GetUser(ctx, req.(*GetOrganizationUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).AddUser(ctx, req.(*OrganizationUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).UpdateUser(ctx, req.(*OrganizationUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrganizationUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Organization/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).DeleteUser(ctx, req.(*DeleteOrganizationUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Organization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Organization",
	HandlerType: (*OrganizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Organization_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Organization_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Organization_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Organization_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Organization_Delete_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Organization_ListUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Organization_GetUser_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Organization_AddUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Organization_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Organization_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organization.proto",
}

func init() { proto.RegisterFile("organization.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0x65, 0xb3, 0xc9, 0xa6, 0xb9, 0x15, 0x85, 0xb1, 0x34, 0x9b, 0x6d, 0xd2, 0xc4, 0x81, 0x4a,
	0xa8, 0x92, 0x60, 0xf5, 0x41, 0x7c, 0x2b, 0xad, 0x44, 0x41, 0x2a, 0x2c, 0xf4, 0x49, 0xb1, 0x8c,
	0xd9, 0x69, 0xba, 0x90, 0xec, 0x6e, 0x77, 0x26, 0x4a, 0xac, 0x05, 0xf1, 0x0f, 0xc4, 0x0f, 0x10,
	0xbf, 0xc9, 0x47, 0x5f, 0xfd, 0x0a, 0x9f, 0x64, 0x67, 0x36, 0x71, 0x9a, 0xec, 0x6c, 0x42, 0xd1,
	0xb7, 0xce, 0xdc, 0xc9, 0x3d, 0xf7, 0x9c, 0x7b, 0xee, 0xdd, 0x02, 0x0a, 0xe3, 0x01, 0x09, 0xfc,
	0x0f, 0x84, 0xfb, 0x61, 0xd0, 0x89, 0xe2, 0x90, 0x87, 0xc8, 0x24, 0x91, 0xef, 0xd4, 0x07, 0x61,
	0x38, 0x18, 0xd2, 0x2e, 0x89, 0xfc, 0x2e, 0x09, 0x82, 0x90, 0x8b, 0x17, 0x4c, 0x3e, 0xc1, 0x27,
	0x50, 0x7d, 0xe1, 0x33, 0xfe, 0x52, 0xf9, 0xb1, 0x4b, 0xcf, 0xc7, 0x94, 0x71, 0xb4, 0x01, 0xa5,
	0xa1, 0x3f, 0xf2, 0xb9, 0x6d, 0xb4, 0x8c, 0x76, 0xc9, 0x95, 0x07, 0xb4, 0x09, 0x56, 0x78, 0x7a,
	0xca, 0x28, 0xb7, 0x0b, 0xe2, 0x3a, 0x3d, 0x25, 0xf7, 0x8c, 0x92, 0xb8, 0x7f, 0x66, 0x9b, 0x2d,
	0xa3, 0x5d, 0x71, 0xd3, 0x13, 0xde, 0x81, 0xdb, 0x59, 0xc9, 0x6f, 0x42, 0xc1, 0xf7, 0x44, 0x66,
	0xd3, 0x2d, 0xf8, 0x1e, 0xfe, 0x69, 0x40, 0xb5, 0x47, 0xe7, 0xea, 0x60, 0x51, 0x18, 0x30, 0x3a,
	0xff, 0x16, 0x21, 0x28, 0x06, 0x64, 0x44, 0x45, 0x01, 0x15, 0x57, 0xfc, 0x8d, 0x5a, 0xb0, 0xee,
	0xf9, 0x2c, 0x1a, 0x92, 0xc9, 0x51, 0x12, 0x92, 0x35, 0xa8, 0x57, 0xa8, 0x0d, 0xb7, 0xfa, 0x24,
	0x78, 0x46, 0xde, 0xd1, 0x1e, 0xe1, 0xf4, 0x3d, 0x99, 0x30, 0xbb, 0xd8, 0x32, 0xda, 0x6b, 0xee,
	0xfc, 0x35, 0xaa, 0x43, 0xa5, 0x1f, 0x53, 0xc2, 0xa9, 0xb7, 0xcf, 0xed, 0x92, 0xc8, 0xf4, 0xf7,
	0x22, 0x89, 0x8e, 0x23, 0x2f, 0x8d, 0x5a, 0x32, 0x3a, 0xbb, 0x48, 0x44, 0x0b, 0xe3, 0xc1, 0x51,
	0x6c, 0x97, 0x45, 0x44, 0x1e, 0xf0, 0x17, 0x03, 0x6a, 0x07, 0x22, 0x43, 0x96, 0x16, 0x53, 0x3e,
	0x86, 0x9e, 0x4f, 0x61, 0x25, 0x3e, 0x66, 0x36, 0x9f, 0x59, 0x4d, 0x45, 0xb5, 0xa6, 0xfb, 0xe0,
	0x64, 0x95, 0x94, 0xad, 0x39, 0xfe, 0x6e, 0x40, 0xed, 0x58, 0xb0, 0x5c, 0xa1, 0x9b, 0xff, 0xbd,
	0x43, 0x33, 0x46, 0x25, 0x95, 0x51, 0x04, 0xf6, 0xa2, 0x97, 0x53, 0x3e, 0xdb, 0x00, 0x3c, 0xe4,
	0x64, 0x78, 0x10, 0x8e, 0x83, 0xa9, 0xa3, 0x95, 0x1b, 0xf4, 0x08, 0xac, 0x98, 0xb2, 0xf1, 0x30,
	0xb1, 0xb5, 0xd9, 0x5e, 0xdf, 0xab, 0x77, 0x48, 0xe4, 0x77, 0x34, 0x8e, 0x74, 0xd3, 0xb7, 0x78,
	0x0b, 0x6a, 0x6a, 0xfc, 0xe9, 0x28, 0xe2, 0x93, 0xe9, 0x23, 0xfc, 0x0a, 0xaa, 0x6a, 0xf0, 0x98,
	0xd1, 0x58, 0xa7, 0xd7, 0x26, 0x58, 0x63, 0x46, 0xe3, 0xe7, 0x87, 0x42, 0x31, 0xd3, 0x4d, 0x4f,
	0xc8, 0x86, 0xb2, 0xcf, 0xf6, 0xbd, 0x91, 0x1f, 0xa4, 0xbd, 0x9d, 0x1e, 0x71, 0x0f, 0x1a, 0x87,
	0x74, 0x48, 0xaf, 0xb6, 0xe3, 0x1a, 0x10, 0xf8, 0x35, 0xd4, 0xe7, 0x45, 0x4b, 0xd2, 0x30, 0x5d,
	0x9e, 0xd9, 0x56, 0x28, 0x64, 0x6f, 0x05, 0x53, 0xdd, 0x0a, 0xf8, 0x10, 0x9c, 0x39, 0x0d, 0xaf,
	0x53, 0xe3, 0x37, 0x03, 0xb6, 0x32, 0xd3, 0x68, 0x16, 0x84, 0x03, 0x6b, 0xc9, 0x2f, 0x15, 0x0b,
	0xce, 0xce, 0x7a, 0x49, 0xaf, 0x8e, 0x7d, 0x31, 0x77, 0xec, 0x4b, 0x73, 0x63, 0x8f, 0x27, 0xd0,
	0xd0, 0xa8, 0xb8, 0xa2, 0xff, 0x1e, 0xcf, 0xf9, 0xaf, 0x95, 0xe5, 0x3f, 0x95, 0xf4, 0xd4, 0x83,
	0x7b, 0xbf, 0xd7, 0xe0, 0x86, 0xfa, 0x08, 0x9d, 0x40, 0x31, 0xa9, 0x05, 0x49, 0x0b, 0x6b, 0xb6,
	0xbb, 0xd3, 0xd0, 0x44, 0x53, 0xf3, 0x3a, 0x9f, 0x7f, 0xfc, 0xfa, 0x5a, 0xd8, 0x40, 0x48, 0x7c,
	0x37, 0xd4, 0x6f, 0x0b, 0x43, 0x6f, 0xc0, 0xec, 0x51, 0x8e, 0x6c, 0x91, 0x21, 0x2b, 0x77, 0xee,
	0xf0, 0xe0, 0xa6, 0x48, 0x5d, 0x43, 0xd5, 0xc5, 0xd4, 0xdd, 0x0b, 0xdf, 0xbb, 0x44, 0x67, 0x60,
	0xc9, 0xcd, 0x84, 0xb6, 0x45, 0x22, 0xed, 0xe6, 0x74, 0x9a, 0xda, 0x78, 0x8a, 0xd5, 0x10, 0x58,
	0x55, 0x9c, 0x41, 0xe3, 0x89, 0xb1, 0x8b, 0x86, 0x60, 0xc9, 0xa5, 0x96, 0x22, 0x69, 0x37, 0x9c,
	0xb3, 0xbd, 0x40, 0xf6, 0xea, 0xb0, 0x63, 0x01, 0x54, 0x77, 0x74, 0xa4, 0x12, 0xb4, 0x3e, 0x58,
	0x72, 0x66, 0x73, 0xa4, 0x5b, 0x86, 0x93, 0x8a, 0xb7, 0xab, 0x15, 0x6f, 0x02, 0x95, 0xa4, 0xa9,
	0xc2, 0x7d, 0xe8, 0x4e, 0x66, 0x93, 0xd5, 0xf9, 0x76, 0x70, 0xde, 0x93, 0x14, 0x74, 0x47, 0x80,
	0x36, 0x51, 0x43, 0x03, 0xda, 0x1d, 0x0b, 0xb4, 0x8f, 0x50, 0xee, 0x51, 0x81, 0x8c, 0x9a, 0x7a,
	0xfb, 0x4a, 0xd8, 0xa5, 0xfe, 0xc6, 0x1d, 0x01, 0xda, 0x46, 0x77, 0x73, 0x41, 0xbb, 0x17, 0x72,
	0x47, 0x5c, 0xa2, 0x73, 0x28, 0xef, 0x7b, 0x9e, 0x40, 0xaf, 0x2f, 0x88, 0xa8, 0x42, 0x2f, 0x93,
	0xb8, 0x2d, 0x80, 0x31, 0xce, 0x67, 0x9b, 0x34, 0xf4, 0x12, 0x40, 0x3a, 0xe6, 0x1f, 0xa0, 0x3e,
	0x10, 0xa8, 0xf7, 0x9c, 0x15, 0xe9, 0x26, 0xf0, 0x9f, 0x0c, 0x00, 0x69, 0x28, 0x81, 0x2f, 0x3b,
	0x99, 0xfb, 0x55, 0x58, 0x5a, 0x45, 0x2a, 0xfa, 0xee, 0x8a, 0x55, 0xbc, 0xb5, 0xc4, 0x7f, 0x91,
	0x0f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xe5, 0xce, 0xd9, 0x7e, 0x0a, 0x00, 0x00,
}
